namespace DropHarvester.Localization;

/// <summary>Spanish (Espanol) string table. Any key not present here falls back to the English base.</summary>
public static partial class LocStrings
{
    public static readonly Dictionary<string, string> Es = new(StringComparer.Ordinal)
    {
        // ----- common -----
        ["Common_Cancel"] = "Cancelar",
        ["Common_Harvest"] = "Cosechar",
        ["Common_Harvesting"] = "Cosechando",

        // ----- tab titles -----
        ["Tab_Status"] = "Estado",
        ["Tab_Inventory"] = "Inventario",
        ["Tab_Channels"] = "Canales",
        ["Tab_Settings"] = "Ajustes",
        ["Tab_Log"] = "Registro",
        ["Tab_Stats"] = "Estadísticas",

        // ----- Status page -----
        ["Status_UpdateReady"] = "Actualización lista",
        ["Status_UpdateNow"] = "Actualizar ahora",
        ["Status_UpdateAvailableTitle"] = "Actualización disponible",
        ["Status_UpdateAvailableDetail"] = "La versión v{0} está disponible - se recomienda encarecidamente actualizar.",
        ["Status_UpdateDownloading"] = "Descargando v{0}...",
        ["Status_Download"] = "Descargar",
        ["Status_Account"] = "CUENTA",
        ["Status_LogIn"] = "Iniciar sesión con Twitch",
        ["Status_LogOut"] = "Cerrar sesión",
        ["Status_AuthorizeHeader"] = "AUTORIZAR ESTA APLICACIÓN",
        ["Status_AuthorizeBody"] = "Se abrió una ventana del navegador. Introduce este código para vincular tu cuenta de Twitch:",
        ["Status_Harvesting"] = "COSECHANDO",
        ["Status_StartHarvesting"] = "Iniciar cosecha",
        ["Status_PauseHarvesting"] = "Pausar cosecha",
        ["Status_Channel"] = "Canal",
        ["Status_Game"] = "Juego",
        ["Status_Campaign"] = "Campaña",
        ["Status_WatchLive"] = "Ver en directo",
        ["Status_CampaignProgress"] = "Progreso de la campaña",
        ["Status_UpNext"] = "A CONTINUACIÓN",
        ["Status_Queue"] = "COLA",
        ["Status_RemoveOverride"] = "Quitar anulación",
        ["Status_AllowNewHigherPriority"] = "Permitir que nuevas campañas de mayor prioridad terminen esta anulación",

        // ----- Settings: language -----
        ["Settings_Language"] = "Idioma",
        ["Settings_LanguageNav"] = "Idioma",

        // ----- notifications -----
        ["Notif_NameDashGame"] = "{0} - {1}",
        ["Notif_DropClaimed"] = "Drop reclamado",
        ["Notif_CampaignComplete"] = "Campaña completada",
        ["Notif_AllHarvested"] = "Todos los drops cosechados",
        ["Notif_AllHarvestedBody"] = "No hay más drops disponibles para cosechar ahora mismo.",
        ["Notif_NewDrop"] = "Nuevo drop disponible",
        ["Notif_LoginExpired"] = "Sesión caducada",
        ["Notif_LoginExpiredBody"] = "Tu sesión de Twitch caducó - por favor inicia sesión de nuevo.",

        // ----- Campaigns / Inventory page -----
        ["Campaigns_Refresh"] = "Actualizar",
        ["Campaigns_Upcoming"] = "Próximos",
        ["Campaigns_Expired"] = "Caducados",
        ["Campaigns_NotLinked"] = "No vinculado",
        ["Campaigns_Finished"] = "Finalizados",
        ["Campaigns_Excluded"] = "Excluidos",
        ["Campaigns_Deduped"] = "De-duplicados",
        ["Campaigns_NoMatch"] = "Ninguna campaña coincide con los filtros actuales.",
        ["Campaigns_Harvesting"] = "Cosechando",
        ["Campaigns_Claimed"] = "Reclamado",
        ["Campaigns_ClaimedBadge"] = "Reclamado",

        // ----- Channels page -----
        ["Channels_Updating"] = "Actualizando...",
        ["Channels_EmptyView"] = "Aún no hay canales rastreados. La cosecha llena esta lista cuando una campaña está activa.",
        ["Channels_Channel"] = "CANAL",
        ["Channels_Official"] = "OFICIAL",
        ["Channels_Viewers"] = "ESPECTADORES",
        ["Channels_Status"] = "ESTADO",
        ["Channels_Watch"] = "Ver",
        ["Channels_Switching"] = "Cambiando...",
        ["Channels_Harvesting"] = "Cosechando",

        // ----- Stats page -----
        ["Stats_DropsClaimed"] = "Drops reclamados",
        ["Stats_CampaignsDone"] = "Campañas completadas",
        ["Stats_WatchTimeSaved"] = "Tiempo cosechando",
        ["Stats_DropsClaimedLast7Days"] = "DROPS RECLAMADOS (ÚLTIMOS 7 DÍAS)",
        ["Stats_ExportCsv"] = "Exportar CSV",
        ["Stats_ExportJson"] = "Exportar JSON",
        ["Stats_RecentHistory"] = "HISTORIAL RECIENTE",
        ["Stats_NoHistoryYet"] = "Aún no hay historial.",

        // ----- Log page -----
        ["Log_Clear"] = "Borrar",
        ["Log_NoLogOutputYet"] = "Aún no hay salida de registro.",

        // ----- Settings page (first-pass machine translation; a native speaker should polish accents) -----
        ["Settings_Settings"] = "AJUSTES",
        ["Settings_NavUpdates"] = "Actualizaciones",
        ["Settings_NavHarvesting"] = "Cosechando",
        ["Settings_NavPriorityGames"] = "Juegos prioritarios",
        ["Settings_NavExcludedGames"] = "Juegos excluidos",
        ["Settings_NavDedupeGames"] = "Juegos sin duplicados",
        ["Settings_NavUnlinkedGames"] = "Juegos sin vincular",
        ["Settings_NavPreferredChannels"] = "Canales preferidos",
        ["Settings_NavAvoidedChannels"] = "Canales evitados",
        ["Settings_NavDropSound"] = "Sonido de Drop",
        ["Settings_NavNotifications"] = "Notificaciones",
        ["Settings_NavWebhookAlerts"] = "Alertas de webhook",
        ["Settings_NavLog"] = "Registro",
        ["Settings_NavApplication"] = "Aplicación",
        ["Settings_NavDebugServer"] = "Servidor de depuración",
        ["Settings_Updates"] = "ACTUALIZACIONES",
        ["Settings_AutoCheckUpdates"] = "Buscar actualizaciones automáticamente al iniciar",
        ["Settings_UpdatesDescription"] = "Busca una nueva versión en GitHub al iniciar y una vez al día. Cuando hay una disponible, un aviso en la pestaña Estado te permite descargarla, y luego instalarla aquí o allí, o se instala sola en el siguiente reinicio.",
        ["Settings_CheckNow"] = "Buscar ahora",
        ["Settings_UpdateNow"] = "Actualizar ahora",
        ["Settings_Harvesting"] = "COSECHANDO",
        ["Settings_HarvestOnlyPriority"] = "Cosechar solo juegos prioritarios",
        ["Settings_PrioritizeEndingSoonest"] = "Priorizar los que terminan antes",
        ["Settings_PrioritizeEndingSoonestDescription"] = "Cosecha la campaña elegible que expire primero - pero respetando la lista de prioridad cuando hay tiempo: un drop prioritario se cosecha antes que uno más próximo siempre que aplazarlo no lo pierda, y un drop no prioritario más próximo solo se elige si no te costará un drop prioritario.",
        ["Settings_PrioritizeByAvailability"] = "Priorizar por disponibilidad",
        ["Settings_PrioritizeByAvailabilityDescription"] = "Solo como desempate: cuando las campañas están igualadas en el orden anterior, cosecha primero aquella cuyo juego tiene menos streamers en directo con Drops habilitados - consiguiendo los drops de streams escasos mientras un canal está en directo y dejando esperar a los juegos abundantes. Nunca anula tu lista de prioridad.",
        ["Settings_HarvestImpossibleDrops"] = "Cosechar drops imposibles",
        ["Settings_HarvestImpossibleDropsDescription"] = "Ver drops que no pueden completarse antes de que termine la campaña (por si se extiende).",
        ["Settings_ShowUnlinkedInChannels"] = "Mostrar juegos sin vincular en Canales",
        ["Settings_ShowUnlinkedInChannelsDescription"] = "Desactivado por defecto. Omitir los canales de juegos sin vincular ahorra consultas al directorio (llamadas a la API).",
        ["Settings_IncludeBadgeEmote"] = "Incluir campañas de insignias/emotes (sin vínculo)",
        ["Settings_AutoClaimChannelPoints"] = "Reclamar automáticamente puntos de canal en el canal visto",
        ["Settings_WhenOverridingHarvest"] = "Al usar anulación, cosechar",
        ["Settings_WhenOverridingHarvestDescription"] = "Lo que hace al pulsar \"Cosechar\" en una campaña: toda la campaña, solo su siguiente drop (luego vuelve a automático), o preguntar cada vez.",
        ["Settings_PriorityGames"] = "JUEGOS PRIORITARIOS (ARRIBA = PRIMERO)",
        ["Settings_StartTypingGameName"] = "Empieza a escribir el nombre de un juego...",
        ["Settings_Add"] = "Añadir",
        ["Settings_DragToReorder"] = "Arrastra por el asa ≡ para reordenar (o usa las flechas). Arriba = cosechado primero.",
        ["Settings_ExcludedGames"] = "JUEGOS EXCLUIDOS",
        ["Settings_ExcludedGamesDescription"] = "Los juegos de esta lista nunca se cosechan - sus campañas de Drops se omiten por completo, incluso cuando el juego está vinculado y tiene streams en directo. Úsala para ignorar juegos de los que no quieres Drops.",
        ["Settings_DedupeGames"] = "JUEGOS SIN DUPLICADOS",
        ["Settings_DedupeGamesDescription"] = "Para los juegos añadidos aquí, omite los drops cuya recompensa ya posees (según el historial de reclamos de Twitch de ~6 meses).",
        ["Settings_HarvestUnlinkedGames"] = "COSECHAR JUEGOS SIN VINCULAR",
        ["Settings_HarvestUnlinkedGamesDescription"] = "Cosecha las campañas de estos juegos incluso sin un vínculo de cuenta. Siempre se cosechan en ÚLTIMO lugar (debajo de cada campaña vinculada), y puede que no acrediten si la campaña realmente requiere un vínculo.",
        ["Settings_PreferredChannels"] = "CANALES PREFERIDOS (⭐)",
        ["Settings_PreferredChannelsDescription"] = "Añade un canal abajo, o haz clic derecho en uno en la pestaña Canales. Cuando un canal preferido está en directo para el juego que se está cosechando y no se requiere un canal oficial de campaña, DropHarvester permanece en él en lugar de en un stream aleatorio de más espectadores - el drop igual acredita, así que apoyas al streamer sin coste para la cosecha. La prioridad/los que terminan antes siguen decidiendo qué juego se cosecha; un canal oficial siempre gana.",
        ["Settings_PreferredChannelPlaceholder"] = "Login del canal (p. ej. ninja)",
        ["Settings_NoChannelsYet"] = "Ninguno todavía - añade uno arriba o haciendo clic derecho en un canal.",
        ["Settings_AvoidedChannels"] = "CANALES EVITADOS (🚫)",
        ["Settings_AvoidedChannelsDescription"] = "Añade un canal abajo, o haz clic derecho en uno en la pestaña Canales. Un canal evitado nunca se usa como espera a menos que sea el único stream con Drops habilitados en directo para el juego en este momento (último recurso).",
        ["Settings_AvoidedChannelPlaceholder"] = "Login del canal (p. ej. algunstreamer)",
        ["Settings_DropClaimedSound"] = "SONIDO DE DROP RECLAMADO",
        ["Settings_PlaySoundOnDropClaimed"] = "Reproducir un sonido cuando se reclama un drop",
        ["Settings_Choose"] = "Elegir...",
        ["Settings_Test"] = "Probar",
        ["Settings_ClearSound"] = "Borrar sonido",
        ["Settings_Volume"] = "Volumen",
        ["Settings_OutputDevice"] = "Dispositivo de salida (Windows puede usar cualquier dispositivo; macOS usa el predeterminado del sistema)",
        ["Settings_DesktopNotifications"] = "NOTIFICACIONES DE ESCRITORIO",
        ["Settings_DropClaimed"] = "Drop reclamado",
        ["Settings_CampaignComplete"] = "Campaña completada",
        ["Settings_AllDropsHarvested"] = "Todos los drops cosechados",
        ["Settings_LoginExpired"] = "Sesión caducada",
        ["Settings_RemoteWebhookAlerts"] = "ALERTAS DE WEBHOOK REMOTO",
        ["Settings_EnableWebhookAlerts"] = "Habilitar alertas de webhook",
        ["Settings_WebhookType"] = "Tipo de webhook",
        ["Settings_WebhookUrl"] = "URL del webhook",
        ["Settings_SendTestMessage"] = "Enviar mensaje de prueba",
        ["Settings_SendOn"] = "ENVIAR CUANDO",
        ["Settings_NewDropAvailable"] = "Nuevo drop disponible para el juego",
        ["Settings_Log"] = "REGISTRO",
        ["Settings_TimestampOnEachLine"] = "Marca de tiempo mostrada en cada línea del registro",
        ["Settings_Application"] = "APLICACIÓN",
        ["Settings_MinimizeToTray"] = "Minimizar a la bandeja al cerrar",
        ["Settings_StartWithSystem"] = "Iniciar con el sistema",
        ["Settings_StartMinimizedToTray"] = "Iniciar minimizado en la bandeja",
        ["Settings_StartMinimizedToTrayDescription"] = "Iniciar directamente en la bandeja en lugar de en pantalla - en cada inicio, ya sea que lo abras tú mismo o se inicie con el sistema.",
        ["Settings_ProxyOptional"] = "Proxy (opcional)",
        ["Settings_ProxyPlaceholder"] = "http://host:puerto",
        ["Settings_DebugServer"] = "SERVIDOR DE DEPURACIÓN",
        ["Settings_RunLocalDebugServer"] = "Ejecutar servidor de depuración local",
        ["Settings_RunLocalDebugServerDescription"] = "Expone el estado en vivo y cada decisión de cosechar/omitir/reclamar como JSON en localhost - para diagnosticar qué está haciendo la app internamente.",
        ["Settings_Port"] = "Puerto",

        // ----- engine status + common log lines -----
        ["Status_Starting"] = "Iniciando...",
        ["Status_Stopped"] = "Detenido",
        ["Status_NoDropsToHarvest"] = "No hay drops para cosechar",
        ["Status_WaitingForStream"] = "Drops disponibles - esperando a que un stream se ponga en directo",
        ["Status_WatchingChannelGame"] = "Viendo {0} - {1}",
        ["Status_ChannelWentOffline"] = "{0} se desconectó",
        ["Log_HarvestingStarted"] = "Cosecha iniciada.",
        ["Log_HarvestingStopped"] = "Cosecha detenida.",
        ["Log_ConnectionReestablished"] = "Conexión restablecida - reanudando la cosecha.",
        ["Log_ConnectionLost"] = "Twitch Drops parece estar caído o se perdió la conexión - cosecha en pausa; se reanudará automáticamente cuando vuelva.",

        // ----- Status/login view-model strings -----
        ["Status_Idle"] = "Inactivo",
        ["Status_NotLoggedIn"] = "Sesión no iniciada",
        ["Status_LoggedInAs"] = "Sesión iniciada como {0} (id {1})",
        ["Status_ConnectionIssue"] = "Twitch Drops tiene problemas o has perdido la conexión. Reanudaremos la cosecha automáticamente cuando se restablezca la conexión.",
        ["Status_DropsOutage"] = "Twitch acepta las visualizaciones, pero ahora mismo no acredita el progreso de los drops (una interrupción del lado de Twitch). La cosecha sigue en marcha y se reanudará automáticamente cuando se solucione.",
        ["Login_Requesting"] = "Solicitando un código de inicio de sesión a Twitch...",
        ["Login_GoToAndEnter"] = "Ve a {0} e introduce el código {1}",
        ["Login_NotCompleted"] = "No se completó el inicio de sesión. Inténtalo de nuevo.",
        ["Login_Cancelled"] = "Inicio de sesión cancelado.",
        ["Login_Failed"] = "Error de inicio de sesión: {0}",
        ["Login_Expired"] = "Tu sesión de Twitch caducó - por favor inicia sesión de nuevo.",
        ["Override_HarvestPrompt"] = "Anulación - cosechar:",
        ["Override_JustNextDrop"] = "Solo el siguiente drop",
        ["Override_EntireCampaign"] = "Toda la campaña",
        ["Override_AskEachTime"] = "Preguntarme cada vez",

        // ----- Inventory load status -----
        ["Inventory_LoadingDrops"] = "Cargando drops... {0}/{1}",
        ["Inventory_Loaded"] = "{0} campañas.",
        ["Inventory_None"] = "No se encontraron campañas.",
        ["Inventory_LoadFailed"] = "Error al cargar: {0}",

        // ----- Channels view-model -----
        ["Channels_CountText"] = "{0} canales en directo en {1} juegos",
        ["Channels_UnknownGame"] = "Desconocido",
        ["Channels_OneLive"] = "1 en directo",
        ["Channels_NLive"] = "{0} en directo",

        // ----- Campaigns view-model -----
        ["Campaigns_ListView"] = "Vista de lista",
        ["Campaigns_GridView"] = "Vista de cuadrícula",
        ["Inventory_LogInFirst"] = "Inicia sesión primero para ver tu inventario.",
        ["Inventory_LoadingCampaigns"] = "Cargando campañas...",

        // ----- Stats view-model -----
        ["Stats_ExportedJson"] = "JSON exportado a {0}",
        ["Stats_ExportedCsv"] = "CSV exportado a {0}",
        ["Stats_Since"] = "Desde {0}",

        // ----- Log view-model -----
        ["Log_Copy"] = "Copiar",
        ["Log_Copied"] = "¡Copiado!",
        ["Log_CopyFailed"] = "Error al copiar",

        // ----- Settings view-model -----
        ["Settings_NoSoundChosen"] = "Ningún sonido elegido",
        ["Settings_ChooseSoundTitle"] = "Elige un sonido para reproducir cuando se reclame un drop",
        ["Settings_SoundPickFailed"] = "No se pudo elegir un archivo: {0}",
        ["Settings_AudioNotAvailable"] = "La reproducción de audio no está disponible en esta plataforma.",
        ["Settings_ChooseSoundFirst"] = "Elige primero un archivo de sonido.",
        ["Settings_SystemDefault"] = "Predeterminado del sistema",
        ["Settings_PlayingOn"] = "Reproduciendo en {0} al {1}...",
        ["Settings_InvalidGameHint"] = "No es un juego válido de Twitch - elige una sugerencia.",
        ["Settings_TimestampDate"] = "Fecha",
        ["Settings_TimestampTime"] = "Hora",
        ["Settings_TimestampDateAndTime"] = "Fecha y hora",
        ["Settings_TimestampTimeAndDate"] = "Hora y fecha",
        ["Settings_Clock12Hour"] = "Reloj de 12 horas",
        ["Settings_Clock24Hour"] = "Reloj de 24 horas",
        ["Settings_CurrentVersion"] = "Tienes la v{0}.",
        ["Settings_UpdateReadyStatus"] = "La actualización v{0} está lista - haz clic en Actualizar ahora para instalar.",
        ["Settings_CheckingForUpdates"] = "Buscando actualizaciones...",
        ["Settings_UpdateServerUnreachable"] = "No se pudo conectar con el servidor de actualizaciones.",
        ["Settings_OnLatestVersion"] = "Tienes la última versión (v{0}).",
        ["Settings_DownloadingUpdate"] = "Descargando actualización v{0}...",
        ["Settings_UpdateReadyAutoInstall"] = "La actualización v{0} está lista - haz clic en Actualizar ahora para instalar, o se instala automáticamente en el siguiente reinicio.",
        ["Settings_UpdateDownloadFailed"] = "Error al descargar la actualización - inténtalo de nuevo.",
        ["Settings_UpdateCheckFailed"] = "Error al buscar actualizaciones.",
        ["Settings_InstallingUpdate"] = "Instalando actualización - la app se reiniciará...",
        ["Settings_InstallerStartFailed"] = "No se pudo iniciar el instalador - se instalará automáticamente en el siguiente reinicio.",
        ["Settings_DebugServerRunning"] = "En ejecución - abre {0} (solo localhost)",
        ["Settings_DebugServerOff"] = "Desactivado",
        ["Settings_Hide"] = "Ocultar",
        ["Settings_Show"] = "Mostrar",
        ["Settings_WebhookGeneric"] = "Genérico",
        ["Settings_Sending"] = "Enviando...",
        ["Settings_WebhookEnterUrlFirst"] = "Introduce primero una URL de webhook.",
        ["Settings_WebhookTestSent"] = "Mensaje de prueba enviado.",
        ["Settings_WebhookReturnedError"] = "El webhook devolvió un error.",
        ["Settings_WebhookFailed"] = "Error: {0}",

        // ----- Twitch model display -----
        ["Model_RemovePreferred"] = "⭐ Quitar preferido",
        ["Model_PreferChannel"] = "⭐ Preferir este canal",
        ["Model_RemoveAvoided"] = "\U0001F6AB Quitar evitado",
        ["Model_AvoidChannel"] = "\U0001F6AB Evitar este canal",
        ["Model_ChannelLive"] = "EN DIRECTO - {0}",
        ["Model_ChannelOffline"] = "desconectado",
        ["Model_DropProgress"] = "{0}/{1} min",
        ["Model_DropProgressSummary"] = "{0}  ({1}/{2} min)",
        ["Model_Remaining"] = "{0} restante",
        ["Model_Linked"] = "Vinculado",
        ["Model_LinkNeeded"] = "Vínculo necesario",
        ["Model_Ends"] = "Termina {0}",
    };
}
