namespace DropHarvester.Localization;

/// <summary>한국어 (Korean) string table. Any key not present falls back to the English base.</summary>
public static partial class LocStrings
{
    public static readonly Dictionary<string, string> Ko = new(StringComparer.Ordinal)
    {
        // ----- common -----
        ["Common_Cancel"] = "취소",
        ["Common_Harvest"] = "수확",
        ["Common_Harvesting"] = "수확 중",

        // ----- tab titles -----
        ["Tab_Status"] = "상태",
        ["Tab_Inventory"] = "인벤토리",
        ["Tab_Channels"] = "채널",
        ["Tab_Settings"] = "설정",
        ["Tab_Log"] = "로그",
        ["Tab_Stats"] = "통계",

        // ----- Status page -----
        ["Status_UpdateReady"] = "업데이트 준비됨",
        ["Status_UpdateNow"] = "지금 업데이트",
        ["Status_UpdateAvailableTitle"] = "업데이트 사용 가능",
        ["Status_UpdateAvailableDetail"] = "버전 v{0}을(를) 사용할 수 있습니다 - 업데이트를 강력히 권장합니다.",
        ["Status_UpdateDownloading"] = "v{0} 다운로드 중...",
        ["Status_Download"] = "다운로드",
        ["Status_Account"] = "계정",
        ["Status_LogIn"] = "Twitch로 로그인",
        ["Status_LogOut"] = "로그아웃",
        ["Status_AuthorizeHeader"] = "이 앱 승인",
        ["Status_AuthorizeBody"] = "브라우저 창이 열렸습니다. Twitch 계정을 연결하려면 이 코드를 입력하세요:",
        ["Status_Harvesting"] = "수확 중",
        ["Status_StartHarvesting"] = "수확 시작",
        ["Status_PauseHarvesting"] = "수확 일시정지",
        ["Status_Channel"] = "채널",
        ["Status_Game"] = "게임",
        ["Status_Campaign"] = "캠페인",
        ["Status_WatchLive"] = "라이브 보기",
        ["Status_CampaignProgress"] = "캠페인 진행률",
        ["Status_UpNext"] = "다음 차례",
        ["Status_Queue"] = "대기열",
        ["Status_RemoveOverride"] = "재정의 제거",
        ["Status_Overriding"] = "재정의 중...",
        ["Changelog_ViewChanges"] = "변경 사항 보기",
        ["Changelog_Title"] = "변경 내용",
        ["Changelog_YouAreHere"] = "현재 버전",
        ["Changelog_Latest"] = "최신",
        ["Changelog_Unavailable"] = "변경 로그를 사용할 수 없습니다.",
        ["Changelog_Update"] = "업데이트",
        ["Changelog_Updating"] = "업데이트 중... {0}",
        ["Changelog_Restarting"] = "다시 시작 중...",
        ["Status_AllowNewHigherPriority"] = "우선순위가 더 높은 새 캠페인이 이 재정의를 종료하도록 허용",

        // ----- Settings: language -----
        ["Settings_Language"] = "언어",
        ["Settings_LanguageNav"] = "언어",

        // ----- notifications -----
        ["Notif_NameDashGame"] = "{0} - {1}",
        ["Notif_DropClaimed"] = "Drop 수령됨",
        ["Notif_CampaignComplete"] = "캠페인 완료",
        ["Notif_AllHarvested"] = "모든 Drop 수확 완료",
        ["Notif_AllHarvestedBody"] = "지금 수확할 수 있는 Drop이 더 이상 없습니다.",
        ["Notif_NewDrop"] = "새로운 Drop 사용 가능",
        ["Notif_LoginExpired"] = "로그인 만료됨",
        ["Notif_LoginExpiredBody"] = "Twitch 세션이 만료되었습니다 - 다시 로그인하세요.",

        // ----- Campaigns / Inventory page -----
        ["Campaigns_Refresh"] = "새로 고침",
        ["Campaigns_Upcoming"] = "예정",
        ["Campaigns_Expired"] = "만료됨",
        ["Campaigns_NotLinked"] = "연결 안 됨",
        ["Campaigns_Finished"] = "완료됨",
        ["Campaigns_Excluded"] = "제외됨",
        ["Campaigns_Deduped"] = "중복 제거됨",
        ["Campaigns_SubOnly"] = "구독 전용",
        ["Campaigns_NoMatch"] = "현재 필터와 일치하는 캠페인이 없습니다.",
        ["Campaigns_Harvesting"] = "수확 중",
        ["Campaigns_Claimed"] = "수령됨",
        ["Campaigns_ClaimedBadge"] = "수령됨",

        // ----- Channels page -----
        ["Channels_Updating"] = "업데이트 중...",
        ["Channels_EmptyView"] = "아직 추적 중인 채널이 없습니다. 캠페인이 활성화되면 수확이 이 목록을 채웁니다.",
        ["Channels_Channel"] = "채널",
        ["Channels_Official"] = "공식",
        ["Channels_Viewers"] = "시청자",
        ["Channels_Status"] = "상태",
        ["Channels_Watch"] = "시청",
        ["Channels_Switching"] = "전환 중...",
        ["Channels_Harvesting"] = "수확 중",

        // ----- Stats page -----
        ["Stats_DropsClaimed"] = "수령한 Drop",
        ["Stats_CampaignsDone"] = "완료한 캠페인",
        ["Stats_WatchTimeSaved"] = "수확에 보낸 시간",
        ["Stats_DropsClaimedLast7Days"] = "수령한 DROP (최근 7일)",
        ["Stats_ExportCsv"] = "CSV 내보내기",
        ["Stats_ExportJson"] = "JSON 내보내기",
        ["Stats_RecentHistory"] = "최근 기록",
        ["Stats_NoHistoryYet"] = "아직 기록이 없습니다.",

        // ----- Log page -----
        ["Log_Clear"] = "지우기",
        ["Log_NoLogOutputYet"] = "아직 로그 출력이 없습니다.",

        // ----- Settings page -----
        ["Settings_Settings"] = "설정",
        ["Settings_NavUpdates"] = "업데이트",
        ["Settings_NavHarvesting"] = "수확",
        ["Settings_NavPriorityGames"] = "우선순위 게임",
        ["Settings_NavExcludedGames"] = "제외 게임",
        ["Settings_NavDedupeGames"] = "중복 제거 게임",
        ["Settings_NavUnlinkedGames"] = "연결 안 된 게임",
        ["Settings_NavPreferredChannels"] = "선호 채널",
        ["Settings_NavAvoidedChannels"] = "회피 채널",
        ["Settings_NavDropSound"] = "Drop 소리",
        ["Settings_NavNotifications"] = "알림",
        ["Settings_NavWebhookAlerts"] = "웹훅 알림",
        ["Settings_NavLog"] = "로그",
        ["Settings_NavApplication"] = "애플리케이션",
        ["Settings_NavDebugServer"] = "디버그 서버",
        ["Settings_Updates"] = "업데이트",
        ["Settings_AutoCheckUpdates"] = "시작 시 자동으로 업데이트 확인",
        ["Settings_UpdatesDescription"] = "시작 시 및 하루에 한 번 GitHub에서 새 버전을 확인합니다. 사용 가능한 경우 상태 탭의 배너에서 다운로드한 다음 여기 또는 거기에서 설치할 수 있으며, 다음 재시작 시 자동으로 설치됩니다.",
        ["Settings_CheckNow"] = "지금 확인",
        ["Settings_UpdateNow"] = "지금 업데이트",
        ["Settings_Harvesting"] = "수확",
        ["Settings_HarvestOnlyPriority"] = "우선순위 게임만 수확",
        ["Settings_PrioritizeEndingSoonest"] = "가장 빨리 종료되는 것 우선",
        ["Settings_PrioritizeEndingSoonestDescription"] = "가장 먼저 만료되는 대상 캠페인을 수확하되, 시간이 있을 때는 우선순위 목록을 여전히 존중합니다: 우선순위 Drop을 미뤄도 놓치지 않는 경우에는 더 빨리 끝나는 것보다 먼저 수확하고, 더 빨리 끝나는 비우선순위 Drop은 우선순위 Drop을 잃지 않을 때만 선택됩니다.",
        ["Settings_PrioritizeByAvailability"] = "가용성 기준 우선순위",
        ["Settings_PrioritizeByAvailabilityDescription"] = "동점 처리 전용: 위 순서에서 캠페인이 동점일 때, 게임의 Drop 지원 라이브 스트리머가 더 적은 쪽을 먼저 수확합니다 - 채널이 라이브인 동안 희소한 스트림의 Drop을 챙기고 풍부한 게임은 기다리게 합니다. 우선순위 목록을 절대 재정의하지 않습니다.",
        ["Settings_HarvestImpossibleDrops"] = "불가능한 Drop 수확",
        ["Settings_HarvestImpossibleDropsDescription"] = "캠페인이 종료되기 전에 완료할 수 없는 Drop도 시청합니다 (연장될 경우를 대비하여).",
        ["Settings_ShowUnlinkedInChannels"] = "채널에 연결 안 된 게임 표시",
        ["Settings_ShowUnlinkedInChannelsDescription"] = "기본적으로 꺼져 있습니다. 연결 안 된 게임의 채널을 건너뛰면 디렉터리 조회(API 호출)를 절약합니다.",
        ["Settings_IncludeBadgeEmote"] = "배지/이모트 캠페인 포함 (연결 불필요)",
        ["Badge_Sub"] = "구독",
        ["Campaigns_BuyDrop"] = "드롭 구매",
        ["Settings_AutoClaimChannelPoints"] = "시청 중인 채널에서 채널 포인트 자동 수령",
        ["Settings_WhenOverridingHarvest"] = "재정의 시 수확 대상",
        ["Settings_WhenOverridingHarvestDescription"] = "캠페인에서 \"수확\"을 클릭하면 하는 작업: 전체 캠페인, 다음 Drop 하나만(그 후 자동으로 복귀), 또는 매번 물어보기.",
        ["Settings_PriorityGames"] = "우선순위 게임 (위쪽 = 먼저)",
        ["Settings_StartTypingGameName"] = "게임 이름을 입력하세요...",
        ["Settings_Add"] = "추가",
        ["Settings_DragToReorder"] = "≡ 핸들을 드래그하여 순서를 변경하세요 (또는 화살표 사용). 위쪽 = 먼저 수확됨.",
        ["Settings_ExcludedGames"] = "제외 게임",
        ["Settings_ExcludedGamesDescription"] = "이 목록에 있는 게임은 절대 수확되지 않습니다 - 게임이 연결되어 있고 라이브 스트림이 있어도 해당 Drop 캠페인은 완전히 건너뜁니다. Drop을 원하지 않는 게임을 무시하는 데 사용하세요.",
        ["Settings_DedupeGames"] = "중복 제거 게임",
        ["Settings_DedupeGamesDescription"] = "여기에 추가된 게임의 경우, 이미 소유한 보상(Twitch의 약 6개월 수령 기록 기준)의 Drop은 건너뜁니다.",
        ["Settings_HarvestUnlinkedGames"] = "연결 안 된 게임 수확",
        ["Settings_HarvestUnlinkedGamesDescription"] = "계정 연결 없이도 이 게임들의 캠페인을 수확합니다. 항상 마지막으로 수확되며(모든 연결된 캠페인 아래), 캠페인이 실제로 연결을 요구하는 경우 지급되지 않을 수 있습니다.",
        ["Settings_PreferredChannels"] = "선호 채널 (⭐)",
        ["Settings_PreferredChannelsDescription"] = "아래에서 채널을 추가하거나, 채널 탭에서 채널을 우클릭하세요. 선호 채널이 수확 중인 게임에 대해 라이브이고 공식 캠페인 채널이 필요하지 않을 때, DropHarvester는 무작위 상위 시청자 스트림 대신 그 채널에서 대기합니다 - Drop은 여전히 지급되므로 수확에 아무런 비용 없이 스트리머를 지원할 수 있습니다. 우선순위/가장 빨리 종료가 여전히 어떤 게임을 수확할지 결정하며, 공식 채널이 항상 우선합니다.",
        ["Settings_PreferredChannelPlaceholder"] = "채널 로그인 (예: ninja)",
        ["Settings_NoChannelsYet"] = "아직 없습니다 - 위에서 추가하거나 채널을 우클릭하세요.",
        ["Settings_AvoidedChannels"] = "회피 채널 (🚫)",
        ["Settings_AvoidedChannelsDescription"] = "아래에서 채널을 추가하거나, 채널 탭에서 채널을 우클릭하세요. 회피 채널은 지금 해당 게임에 대해 Drop 지원 라이브 스트림이 그것뿐인 경우(최후의 수단)를 제외하고는 절대 대기하지 않습니다.",
        ["Settings_AvoidedChannelPlaceholder"] = "채널 로그인 (예: somestreamer)",
        ["Settings_DropClaimedSound"] = "DROP 수령 소리",
        ["Settings_PlaySoundOnDropClaimed"] = "Drop 수령 시 소리 재생",
        ["Settings_Choose"] = "선택...",
        ["Settings_Test"] = "테스트",
        ["Settings_ClearSound"] = "소리 지우기",
        ["Settings_Volume"] = "볼륨",
        ["Settings_OutputDevice"] = "출력 장치 (Windows는 모든 장치를 지정할 수 있으며, macOS는 시스템 기본값을 사용합니다)",
        ["Settings_DesktopNotifications"] = "데스크톱 알림",
        ["Settings_DropClaimed"] = "Drop 수령됨",
        ["Settings_CampaignComplete"] = "캠페인 완료",
        ["Settings_AllDropsHarvested"] = "모든 Drop 수확 완료",
        ["Settings_LoginExpired"] = "로그인 만료됨",
        ["Settings_RemoteWebhookAlerts"] = "원격 웹훅 알림",
        ["Settings_EnableWebhookAlerts"] = "웹훅 알림 활성화",
        ["Settings_WebhookType"] = "웹훅 유형",
        ["Settings_WebhookUrl"] = "웹훅 URL",
        ["Settings_SendTestMessage"] = "테스트 메시지 보내기",
        ["Settings_SendOn"] = "전송 조건",
        ["Settings_NewDropAvailable"] = "게임에 새로운 Drop 사용 가능",
        ["Settings_Log"] = "로그",
        ["Settings_TimestampOnEachLine"] = "각 로그 줄에 타임스탬프 표시",
        ["Settings_Application"] = "애플리케이션",
        ["Settings_MinimizeToTray"] = "닫을 때 트레이로 최소화",
        ["Settings_StartWithSystem"] = "시스템과 함께 시작",
        ["Settings_StartMinimizedToTray"] = "트레이로 최소화된 상태로 시작",
        ["Settings_StartMinimizedToTrayDescription"] = "화면에 표시하지 않고 바로 트레이로 실행합니다 - 직접 열든 시스템과 함께 시작하든 매번 실행 시.",
        ["Settings_ProxyOptional"] = "프록시 (선택 사항)",
        ["Settings_ProxyPlaceholder"] = "http://host:port",
        ["Settings_DebugServer"] = "디버그 서버",
        ["Settings_RunLocalDebugServer"] = "로컬 디버그 서버 실행",
        ["Settings_RunLocalDebugServerDescription"] = "라이브 상태와 모든 수확/건너뛰기/수령 결정을 localhost에서 JSON으로 노출합니다 - 앱이 내부적으로 무엇을 하는지 진단하기 위한 것입니다.",
        ["Settings_Port"] = "포트",

        // ----- engine status + common log lines -----
        ["Status_Starting"] = "시작 중...",
        ["Status_Stopped"] = "중지됨",
        ["Status_NoDropsToHarvest"] = "수확할 Drop 없음",
        ["Status_WaitingForStream"] = "Drop 사용 가능 - 스트림이 온라인이 되기를 기다리는 중",
        ["Status_WatchingChannelGame"] = "{0} 시청 중 - {1}",
        ["Status_ChannelWentOffline"] = "{0}이(가) 오프라인이 되었습니다",
        ["Log_HarvestingStarted"] = "수확을 시작했습니다.",
        ["Log_HarvestingStopped"] = "수확을 중지했습니다.",
        ["Log_ConnectionReestablished"] = "연결이 다시 설정되었습니다 - 수확을 재개합니다.",
        ["Log_ConnectionLost"] = "Twitch Drops가 다운되었거나 연결이 끊긴 것으로 보입니다 - 수확이 일시정지되었습니다. 복구되면 자동으로 재개됩니다.",

        // ----- Status/login view-model strings -----
        ["Status_Idle"] = "대기 중",
        ["Status_NotLoggedIn"] = "로그인 안 됨",
        ["Status_LoggedInAs"] = "{0}(으)로 로그인됨 (id {1})",
        ["Status_LoggedIn"] = "로그인됨",
        ["Status_AccountDetail"] = "{0} (id {1})",
        ["Status_ConnectionIssue"] = "Twitch Drops에 문제가 있거나 연결이 끊겼습니다. 연결이 다시 설정되면 자동으로 수확을 재개합니다.",
        ["Status_DropsOutage"] = "현재 Twitch가 시청은 받아들이지만 드롭 진행도를 적립하지 않고 있습니다(트위치 측 장애). 수확은 계속 실행되며 복구되면 자동으로 재개됩니다.",
        ["Login_Requesting"] = "Twitch에서 로그인 코드를 요청하는 중...",
        ["Login_GoToAndEnter"] = "{0}(으)로 이동하여 코드 {1}을(를) 입력하세요",
        ["Login_NotCompleted"] = "로그인이 완료되지 않았습니다. 다시 시도하세요.",
        ["Login_Cancelled"] = "로그인이 취소되었습니다.",
        ["Login_Failed"] = "로그인 실패: {0}",
        ["Login_Expired"] = "Twitch 세션이 만료되었습니다 - 다시 로그인하세요.",
        ["Override_HarvestPrompt"] = "재정의 - 수확:",
        ["Override_JustNextDrop"] = "다음 Drop 하나만",
        ["Override_EntireCampaign"] = "전체 캠페인",
        ["Override_AskEachTime"] = "매번 물어보기",

        // ----- Inventory load status -----
        ["Inventory_LoadingDrops"] = "Drop 불러오는 중... {0}/{1}",
        ["Inventory_Loaded"] = "캠페인 {0}개.",
        ["Inventory_None"] = "캠페인을 찾을 수 없습니다.",
        ["Inventory_LoadFailed"] = "불러오기 실패: {0}",

        // ----- Channels view-model -----
        ["Channels_CountText"] = "게임 {1}개에 걸쳐 라이브 채널 {0}개",
        ["Channels_UnknownGame"] = "알 수 없음",
        ["Channels_OneLive"] = "1개 라이브",
        ["Channels_NLive"] = "{0}개 라이브",

        // ----- Campaigns view-model -----
        ["Campaigns_ListView"] = "목록 보기",
        ["Campaigns_GridView"] = "그리드 보기",
        ["Inventory_LogInFirst"] = "인벤토리를 보려면 먼저 로그인하세요.",
        ["Inventory_LoadingCampaigns"] = "캠페인 불러오는 중...",

        // ----- Stats view-model -----
        ["Stats_ExportedJson"] = "JSON을 {0}에 내보냈습니다",
        ["Stats_ExportedCsv"] = "CSV를 {0}에 내보냈습니다",
        ["Stats_Since"] = "{0} 이후",

        // ----- Log view-model -----
        ["Log_Copy"] = "복사",
        ["Log_Copied"] = "복사됨!",
        ["Log_CopyFailed"] = "복사 실패",

        // ----- Settings view-model -----
        ["Settings_NoSoundChosen"] = "선택된 소리 없음",
        ["Settings_ChooseSoundTitle"] = "Drop 수령 시 재생할 소리 선택",
        ["Settings_SoundPickFailed"] = "파일을 선택할 수 없습니다: {0}",
        ["Settings_AudioNotAvailable"] = "이 플랫폼에서는 오디오 재생을 사용할 수 없습니다.",
        ["Settings_ChooseSoundFirst"] = "먼저 소리 파일을 선택하세요.",
        ["Settings_SystemDefault"] = "시스템 기본값",
        ["Settings_PlayingOn"] = "{1} 볼륨으로 {0}에서 재생 중...",
        ["Settings_InvalidGameHint"] = "유효한 Twitch 게임이 아닙니다 - 제안 항목을 선택하세요.",
        ["Settings_TimestampDate"] = "날짜",
        ["Settings_TimestampTime"] = "시간",
        ["Settings_TimestampDateAndTime"] = "날짜 및 시간",
        ["Settings_TimestampTimeAndDate"] = "시간 및 날짜",
        ["Settings_Clock12Hour"] = "12시간제",
        ["Settings_Clock24Hour"] = "24시간제",
        ["Settings_CurrentVersion"] = "현재 v{0}을(를) 사용 중입니다.",
        ["Settings_UpdateReadyStatus"] = "업데이트 v{0}이(가) 준비되었습니다 - 지금 업데이트를 클릭하여 설치하세요.",
        ["Settings_CheckingForUpdates"] = "업데이트 확인 중...",
        ["Settings_UpdateServerUnreachable"] = "업데이트 서버에 연결할 수 없습니다.",
        ["Settings_OnLatestVersion"] = "최신 버전(v{0})을 사용 중입니다.",
        ["Settings_DownloadingUpdate"] = "업데이트 v{0} 다운로드 중...",
        ["Settings_UpdateReadyAutoInstall"] = "업데이트 v{0}이(가) 준비되었습니다 - 지금 업데이트를 클릭하여 설치하거나, 다음 재시작 시 자동으로 설치됩니다.",
        ["Settings_UpdateDownloadFailed"] = "업데이트 다운로드에 실패했습니다 - 다시 시도하세요.",
        ["Settings_UpdateCheckFailed"] = "업데이트 확인에 실패했습니다.",
        ["Settings_InstallingUpdate"] = "업데이트 설치 중 - 앱이 재시작됩니다...",
        ["Settings_InstallerStartFailed"] = "설치 프로그램을 시작할 수 없습니다 - 다음 재시작 시 자동으로 설치됩니다.",
        ["Settings_DebugServerRunning"] = "실행 중 - {0} 열기 (localhost 전용)",
        ["Settings_DebugServerOff"] = "꺼짐",
        ["Settings_Hide"] = "숨기기",
        ["Settings_Show"] = "표시",
        ["Settings_WebhookGeneric"] = "일반",
        ["Settings_Sending"] = "전송 중...",
        ["Settings_WebhookEnterUrlFirst"] = "먼저 웹훅 URL을 입력하세요.",
        ["Settings_WebhookTestSent"] = "테스트 메시지를 보냈습니다.",
        ["Settings_WebhookReturnedError"] = "웹훅이 오류를 반환했습니다.",
        ["Settings_WebhookFailed"] = "실패: {0}",

        // ----- Twitch model display -----
        ["Model_RemovePreferred"] = "⭐ 선호 제거",
        ["Model_PreferChannel"] = "⭐ 이 채널 선호",
        ["Model_RemoveAvoided"] = "\U0001F6AB 회피 제거",
        ["Model_AvoidChannel"] = "\U0001F6AB 이 채널 회피",
        ["Model_ChannelLive"] = "라이브 - {0}",
        ["Model_ChannelOffline"] = "오프라인",
        ["Model_DropProgress"] = "{0}/{1}분",
        ["Model_DropProgressSummary"] = "{0}  ({1}/{2}분)",
        ["Model_Remaining"] = "{0} 남음",
        ["Model_Linked"] = "연결됨",
        ["Model_LinkNeeded"] = "연결 필요",
        ["Model_Ends"] = "{0} 종료",
    };
}
