namespace DropHarvester.Localization;

/// <summary>Nederlands (Dutch) string table. Any key not present falls back to the English base.</summary>
public static partial class LocStrings
{
    public static readonly Dictionary<string, string> Nl = new(StringComparer.Ordinal)
    {
        // ----- common -----
        ["Common_Cancel"] = "Annuleren",
        ["Common_Harvest"] = "Oogsten",
        ["Common_Harvesting"] = "Bezig met oogsten",

        // ----- tab titles -----
        ["Tab_Status"] = "Status",
        ["Tab_Inventory"] = "Inventaris",
        ["Tab_Channels"] = "Kanalen",
        ["Tab_Settings"] = "Instellingen",
        ["Tab_Log"] = "Logboek",
        ["Tab_Stats"] = "Statistieken",

        // ----- Status page -----
        ["Status_UpdateReady"] = "Update gereed",
        ["Status_UpdateNow"] = "Nu bijwerken",
        ["Status_UpdateAvailableTitle"] = "Update beschikbaar",
        ["Status_UpdateAvailableDetail"] = "Versie v{0} is beschikbaar - het wordt sterk aanbevolen om bij te werken.",
        ["Status_UpdateDownloading"] = "v{0} downloaden...",
        ["Status_Download"] = "Downloaden",
        ["Status_Account"] = "ACCOUNT",
        ["Status_LogIn"] = "Inloggen met Twitch",
        ["Status_LogOut"] = "Uitloggen",
        ["Status_AuthorizeHeader"] = "AUTORISEER DEZE APP",
        ["Status_AuthorizeBody"] = "Er is een browservenster geopend. Voer deze code in om je Twitch-account te koppelen:",
        ["Status_Harvesting"] = "OOGSTEN",
        ["Status_StartHarvesting"] = "Oogsten starten",
        ["Status_PauseHarvesting"] = "Oogsten pauzeren",
        ["Status_Channel"] = "Kanaal",
        ["Status_Game"] = "Game",
        ["Status_Campaign"] = "Campagne",
        ["Status_CampaignProgress"] = "Campagnevoortgang",
        ["Status_UpNext"] = "VOLGENDE",
        ["Status_Queue"] = "WACHTRIJ",
        ["Status_RemoveOverride"] = "Overschrijving verwijderen",
        ["Status_AllowNewHigherPriority"] = "Nieuwe campagnes met hogere prioriteit deze overschrijving laten beëindigen",

        // ----- Settings: language -----
        ["Settings_Language"] = "Taal",
        ["Settings_LanguageNav"] = "Taal",

        // ----- notifications -----
        ["Notif_NameDashGame"] = "{0} - {1}",
        ["Notif_DropClaimed"] = "Drop geclaimd",
        ["Notif_CampaignComplete"] = "Campagne voltooid",
        ["Notif_AllHarvested"] = "Alle drops geoogst",
        ["Notif_AllHarvestedBody"] = "Er zijn op dit moment geen drops meer beschikbaar om te oogsten.",
        ["Notif_NewDrop"] = "Nieuwe drop beschikbaar",
        ["Notif_LoginExpired"] = "Login verlopen",
        ["Notif_LoginExpiredBody"] = "Je Twitch-sessie is verlopen - log opnieuw in.",

        // ----- Campaigns / Inventory page -----
        ["Campaigns_Refresh"] = "Vernieuwen",
        ["Campaigns_Upcoming"] = "Binnenkort",
        ["Campaigns_Expired"] = "Verlopen",
        ["Campaigns_NotLinked"] = "Niet gekoppeld",
        ["Campaigns_Finished"] = "Voltooid",
        ["Campaigns_Excluded"] = "Uitgesloten",
        ["Campaigns_Deduped"] = "Ontdubbeld",
        ["Campaigns_NoMatch"] = "Geen campagnes voldoen aan de huidige filters.",
        ["Campaigns_Harvesting"] = "Bezig met oogsten",
        ["Campaigns_Claimed"] = "Geclaimd",
        ["Campaigns_ClaimedBadge"] = "Geclaimd",

        // ----- Channels page -----
        ["Channels_Updating"] = "Bijwerken...",
        ["Channels_EmptyView"] = "Nog geen kanalen gevolgd. Oogsten vult dit zodra een campagne actief is.",
        ["Channels_Channel"] = "KANAAL",
        ["Channels_Official"] = "OFFICIEEL",
        ["Channels_Viewers"] = "KIJKERS",
        ["Channels_Status"] = "STATUS",
        ["Channels_Watch"] = "Bekijken",
        ["Channels_Switching"] = "Wisselen...",
        ["Channels_Harvesting"] = "Bezig met oogsten",

        // ----- Stats page -----
        ["Stats_DropsClaimed"] = "Drops geclaimd",
        ["Stats_CampaignsDone"] = "Campagnes voltooid",
        ["Stats_WatchTimeSaved"] = "Kijktijd bespaard",
        ["Stats_DropsClaimedLast7Days"] = "DROPS GECLAIMD (LAATSTE 7 DAGEN)",
        ["Stats_ExportCsv"] = "CSV exporteren",
        ["Stats_ExportJson"] = "JSON exporteren",
        ["Stats_RecentHistory"] = "RECENTE GESCHIEDENIS",
        ["Stats_NoHistoryYet"] = "Nog geen geschiedenis.",

        // ----- Log page -----
        ["Log_Clear"] = "Wissen",
        ["Log_NoLogOutputYet"] = "Nog geen loguitvoer.",

        // ----- Settings page -----
        ["Settings_Settings"] = "INSTELLINGEN",
        ["Settings_NavUpdates"] = "Updates",
        ["Settings_NavHarvesting"] = "Oogsten",
        ["Settings_NavPriorityGames"] = "Prioriteitsgames",
        ["Settings_NavExcludedGames"] = "Uitgesloten games",
        ["Settings_NavDedupeGames"] = "Ontdubbel-games",
        ["Settings_NavUnlinkedGames"] = "Niet-gekoppelde games",
        ["Settings_NavPreferredChannels"] = "Voorkeurskanalen",
        ["Settings_NavAvoidedChannels"] = "Vermeden kanalen",
        ["Settings_NavDropSound"] = "Drop-geluid",
        ["Settings_NavNotifications"] = "Meldingen",
        ["Settings_NavWebhookAlerts"] = "Webhook-waarschuwingen",
        ["Settings_NavLog"] = "Logboek",
        ["Settings_NavApplication"] = "Applicatie",
        ["Settings_NavDebugServer"] = "Debugserver",
        ["Settings_Updates"] = "UPDATES",
        ["Settings_AutoCheckUpdates"] = "Automatisch op updates controleren bij het opstarten",
        ["Settings_UpdatesDescription"] = "Controleert bij het opstarten en eenmaal per dag op GitHub op een nieuwe versie. Als er een beschikbaar is, kun je die via een banner op het tabblad Status downloaden en hier of daar installeren - of ze installeert zich bij de volgende herstart.",
        ["Settings_CheckNow"] = "Nu controleren",
        ["Settings_UpdateNow"] = "Nu bijwerken",
        ["Settings_Harvesting"] = "OOGSTEN",
        ["Settings_HarvestOnlyPriority"] = "Alleen prioriteitsgames oogsten",
        ["Settings_PrioritizeEndingSoonest"] = "Prioriteit geven aan wat het eerst afloopt",
        ["Settings_PrioritizeEndingSoonestDescription"] = "Oogst de in aanmerking komende campagne die het eerst verloopt - maar respecteer nog steeds de prioriteitslijst wanneer er tijd is: een prioriteitsdrop wordt vóór een eerder aflopende geoogst zolang uitstellen die niet zou doen verliezen, en een eerder aflopende niet-prioriteitsdrop wordt alleen gekozen als die je geen prioriteitsdrop kost.",
        ["Settings_PrioritizeByAvailability"] = "Prioriteit geven op beschikbaarheid",
        ["Settings_PrioritizeByAvailabilityDescription"] = "Alleen als tiebreaker: wanneer campagnes verder gelijk staan in de bovenstaande volgorde, oogst dan eerst degene waarvan de game minder live streamers met drops ingeschakeld heeft - schaarse-stream drops pakken terwijl een kanaal live is en overvloedige games laten wachten. Overschrijft nooit je prioriteitslijst.",
        ["Settings_HarvestImpossibleDrops"] = "Onmogelijke drops oogsten",
        ["Settings_HarvestImpossibleDropsDescription"] = "Bekijk drops die niet kunnen worden voltooid voordat de campagne afloopt (voor het geval die wordt verlengd).",
        ["Settings_ShowUnlinkedInChannels"] = "Niet-gekoppelde games tonen in Kanalen",
        ["Settings_ShowUnlinkedInChannelsDescription"] = "Standaard uit. Het overslaan van kanalen van niet-gekoppelde games bespaart mapopzoekingen (API-aanroepen).",
        ["Settings_IncludeBadgeEmote"] = "Badge-/emote-campagnes opnemen (geen koppeling)",
        ["Settings_AutoClaimChannelPoints"] = "Kanaalpunten automatisch claimen op bekeken kanaal",
        ["Settings_WhenOverridingHarvest"] = "Bij overschrijven, oogst",
        ["Settings_WhenOverridingHarvestDescription"] = "Wat er gebeurt als je op \"Oogsten\" klikt bij een campagne: de hele campagne, alleen de volgende drop (daarna terug naar automatisch), of elke keer vragen.",
        ["Settings_PriorityGames"] = "PRIORITEITSGAMES (BOVENAAN = EERST)",
        ["Settings_StartTypingGameName"] = "Begin met het typen van een gamenaam...",
        ["Settings_Add"] = "Toevoegen",
        ["Settings_DragToReorder"] = "Sleep aan de ≡ greep om de volgorde te wijzigen (of gebruik de pijltjes). Bovenaan = eerst geoogst.",
        ["Settings_ExcludedGames"] = "UITGESLOTEN GAMES",
        ["Settings_ExcludedGamesDescription"] = "Games op deze lijst worden nooit geoogst - hun drop-campagnes worden volledig overgeslagen, zelfs wanneer de game gekoppeld is en live streams heeft. Gebruik dit om games te negeren waarvoor je geen drops wilt.",
        ["Settings_DedupeGames"] = "ONTDUBBEL-GAMES",
        ["Settings_DedupeGamesDescription"] = "Voor games die hier zijn toegevoegd, sla drops over waarvan je de beloning al bezit (uit Twitch' claimgeschiedenis van ~6 maanden).",
        ["Settings_HarvestUnlinkedGames"] = "NIET-GEKOPPELDE GAMES OOGSTEN",
        ["Settings_HarvestUnlinkedGamesDescription"] = "Oogst de campagnes van deze games ook zonder accountkoppeling. Worden altijd als LAATSTE geoogst (onder elke gekoppelde campagne), en worden mogelijk niet gecrediteerd als de campagne daadwerkelijk een koppeling vereist.",
        ["Settings_PreferredChannels"] = "VOORKEURSKANALEN (⭐)",
        ["Settings_PreferredChannelsDescription"] = "Voeg hieronder een kanaal toe, of klik met de rechtermuisknop op een kanaal in het tabblad Kanalen. Wanneer een voorkeurskanaal live is voor de game die wordt geoogst en er geen officieel campagnekanaal vereist is, blijft DropHarvester daarop hangen in plaats van op een willekeurige stream met veel kijkers - de drop wordt nog steeds gecrediteerd, dus je steunt de streamer zonder dat het het oogsten kost. Prioriteit/eerst-aflopend bepaalt nog steeds welke game wordt geoogst; een officieel kanaal wint altijd.",
        ["Settings_PreferredChannelPlaceholder"] = "Kanaallogin (bijv. ninja)",
        ["Settings_NoChannelsYet"] = "Nog geen - voeg er hierboven een toe of klik met de rechtermuisknop op een kanaal.",
        ["Settings_AvoidedChannels"] = "VERMEDEN KANALEN (🚫)",
        ["Settings_AvoidedChannelsDescription"] = "Voeg hieronder een kanaal toe, of klik met de rechtermuisknop op een kanaal in het tabblad Kanalen. Op een vermeden kanaal wordt nooit blijven hangen, tenzij het op dit moment de enige live stream met drops ingeschakeld is voor de game (laatste redmiddel).",
        ["Settings_AvoidedChannelPlaceholder"] = "Kanaallogin (bijv. somestreamer)",
        ["Settings_DropClaimedSound"] = "GELUID BIJ GECLAIMDE DROP",
        ["Settings_PlaySoundOnDropClaimed"] = "Een geluid afspelen wanneer een drop wordt geclaimd",
        ["Settings_Choose"] = "Kiezen...",
        ["Settings_Test"] = "Testen",
        ["Settings_ClearSound"] = "Geluid wissen",
        ["Settings_Volume"] = "Volume",
        ["Settings_OutputDevice"] = "Uitvoerapparaat (Windows kan elk apparaat aansturen; macOS gebruikt de systeemstandaard)",
        ["Settings_DesktopNotifications"] = "BUREAUBLADMELDINGEN",
        ["Settings_DropClaimed"] = "Drop geclaimd",
        ["Settings_CampaignComplete"] = "Campagne voltooid",
        ["Settings_AllDropsHarvested"] = "Alle drops geoogst",
        ["Settings_LoginExpired"] = "Login verlopen",
        ["Settings_RemoteWebhookAlerts"] = "EXTERNE WEBHOOK-WAARSCHUWINGEN",
        ["Settings_EnableWebhookAlerts"] = "Webhook-waarschuwingen inschakelen",
        ["Settings_WebhookType"] = "Webhook-type",
        ["Settings_WebhookUrl"] = "Webhook-URL",
        ["Settings_SendTestMessage"] = "Testbericht verzenden",
        ["Settings_SendOn"] = "VERZENDEN BIJ",
        ["Settings_NewDropAvailable"] = "Nieuwe drop beschikbaar voor game",
        ["Settings_Log"] = "LOGBOEK",
        ["Settings_TimestampOnEachLine"] = "Tijdstempel op elke logregel weergegeven",
        ["Settings_Application"] = "APPLICATIE",
        ["Settings_MinimizeToTray"] = "Bij sluiten minimaliseren naar systeemvak",
        ["Settings_StartWithSystem"] = "Starten met het systeem",
        ["Settings_StartMinimizedToTray"] = "Geminimaliseerd naar het systeemvak starten",
        ["Settings_StartMinimizedToTrayDescription"] = "Start rechtstreeks naar het systeemvak in plaats van op het scherm - bij elke start, of je het nu zelf opent of het met het systeem start.",
        ["Settings_ProxyOptional"] = "Proxy (optioneel)",
        ["Settings_ProxyPlaceholder"] = "http://host:port",
        ["Settings_DebugServer"] = "DEBUGSERVER",
        ["Settings_RunLocalDebugServer"] = "Lokale debugserver uitvoeren",
        ["Settings_RunLocalDebugServerDescription"] = "Stelt live status en elke oogst-/overslaan-/claimbeslissing beschikbaar als JSON op localhost - voor het diagnosticeren van wat de app onder de motorkap doet.",
        ["Settings_Port"] = "Poort",

        // ----- engine status + common log lines -----
        ["Status_Starting"] = "Starten...",
        ["Status_Stopped"] = "Gestopt",
        ["Status_NoDropsToHarvest"] = "Geen drops om te oogsten",
        ["Status_WaitingForStream"] = "Drops beschikbaar - wachten tot een stream online komt",
        ["Status_WatchingChannelGame"] = "Bekijken {0} - {1}",
        ["Status_ChannelWentOffline"] = "{0} is offline gegaan",
        ["Log_HarvestingStarted"] = "Oogsten gestart.",
        ["Log_HarvestingStopped"] = "Oogsten gestopt.",
        ["Log_ConnectionReestablished"] = "Verbinding hersteld - oogsten wordt hervat.",
        ["Log_ConnectionLost"] = "Twitch Drops lijken plat te liggen of de verbinding is verbroken - oogsten gepauzeerd; wordt automatisch hervat zodra het terug is.",

        // ----- Status/login view-model strings -----
        ["Status_Idle"] = "Inactief",
        ["Status_NotLoggedIn"] = "Niet ingelogd",
        ["Status_LoggedInAs"] = "Ingelogd als {0} (id {1})",
        ["Status_ConnectionIssue"] = "Twitch Drops ondervinden problemen of je hebt de verbinding verloren. We hervatten het oogsten automatisch zodra de verbinding is hersteld.",
        ["Login_Requesting"] = "Een logincode aanvragen bij Twitch...",
        ["Login_GoToAndEnter"] = "Ga naar {0} en voer code {1} in",
        ["Login_NotCompleted"] = "Login is niet voltooid. Probeer het opnieuw.",
        ["Login_Cancelled"] = "Login geannuleerd.",
        ["Login_Failed"] = "Login mislukt: {0}",
        ["Login_Expired"] = "Je Twitch-sessie is verlopen - log opnieuw in.",
        ["Override_HarvestPrompt"] = "Overschrijven - oogst:",
        ["Override_JustNextDrop"] = "Alleen de volgende drop",
        ["Override_EntireCampaign"] = "Hele campagne",
        ["Override_AskEachTime"] = "Vraag het me elke keer",

        // ----- Inventory load status -----
        ["Inventory_LoadingDrops"] = "Drops laden... {0}/{1}",
        ["Inventory_Loaded"] = "{0} campagnes.",
        ["Inventory_None"] = "Geen campagnes gevonden.",
        ["Inventory_LoadFailed"] = "Laden mislukt: {0}",

        // ----- Channels view-model -----
        ["Channels_CountText"] = "{0} live kanalen verdeeld over {1} games",
        ["Channels_UnknownGame"] = "Onbekend",
        ["Channels_OneLive"] = "1 live",
        ["Channels_NLive"] = "{0} live",

        // ----- Campaigns view-model -----
        ["Campaigns_ListView"] = "Lijstweergave",
        ["Campaigns_GridView"] = "Rasterweergave",
        ["Inventory_LogInFirst"] = "Log eerst in om je inventaris te zien.",
        ["Inventory_LoadingCampaigns"] = "Campagnes laden...",

        // ----- Stats view-model -----
        ["Stats_ExportedJson"] = "JSON geëxporteerd naar {0}",
        ["Stats_ExportedCsv"] = "CSV geëxporteerd naar {0}",
        ["Stats_Since"] = "Sinds {0}",

        // ----- Log view-model -----
        ["Log_Copy"] = "Kopiëren",
        ["Log_Copied"] = "Gekopieerd!",
        ["Log_CopyFailed"] = "Kopiëren mislukt",

        // ----- Settings view-model -----
        ["Settings_NoSoundChosen"] = "Geen geluid gekozen",
        ["Settings_ChooseSoundTitle"] = "Kies een geluid om af te spelen wanneer een drop wordt geclaimd",
        ["Settings_SoundPickFailed"] = "Kon geen bestand kiezen: {0}",
        ["Settings_AudioNotAvailable"] = "Audioweergave is niet beschikbaar op dit platform.",
        ["Settings_ChooseSoundFirst"] = "Kies eerst een geluidsbestand.",
        ["Settings_SystemDefault"] = "Systeemstandaard",
        ["Settings_PlayingOn"] = "Afspelen op {0} op {1}...",
        ["Settings_InvalidGameHint"] = "Geen geldige Twitch-game - kies een suggestie.",
        ["Settings_TimestampDate"] = "Datum",
        ["Settings_TimestampTime"] = "Tijd",
        ["Settings_TimestampDateAndTime"] = "Datum en tijd",
        ["Settings_TimestampTimeAndDate"] = "Tijd en datum",
        ["Settings_Clock12Hour"] = "12-uursklok",
        ["Settings_Clock24Hour"] = "24-uursklok",
        ["Settings_CurrentVersion"] = "Je gebruikt v{0}.",
        ["Settings_UpdateReadyStatus"] = "Update v{0} is gereed - klik op Nu bijwerken om te installeren.",
        ["Settings_CheckingForUpdates"] = "Controleren op updates...",
        ["Settings_UpdateServerUnreachable"] = "Kon de updateserver niet bereiken.",
        ["Settings_OnLatestVersion"] = "Je gebruikt de nieuwste versie (v{0}).",
        ["Settings_DownloadingUpdate"] = "Update v{0} downloaden...",
        ["Settings_UpdateReadyAutoInstall"] = "Update v{0} is gereed - klik op Nu bijwerken om te installeren, of hij wordt automatisch geïnstalleerd bij de volgende herstart.",
        ["Settings_UpdateDownloadFailed"] = "Update-download mislukt - probeer het opnieuw.",
        ["Settings_UpdateCheckFailed"] = "Updatecontrole mislukt.",
        ["Settings_InstallingUpdate"] = "Update installeren - de app wordt opnieuw gestart...",
        ["Settings_InstallerStartFailed"] = "Kon het installatieprogramma niet starten - het wordt automatisch geïnstalleerd bij de volgende herstart.",
        ["Settings_DebugServerRunning"] = "Actief - open {0} (alleen localhost)",
        ["Settings_DebugServerOff"] = "Uit",
        ["Settings_Hide"] = "Verbergen",
        ["Settings_Show"] = "Tonen",
        ["Settings_WebhookGeneric"] = "Algemeen",
        ["Settings_Sending"] = "Verzenden...",
        ["Settings_WebhookEnterUrlFirst"] = "Voer eerst een webhook-URL in.",
        ["Settings_WebhookTestSent"] = "Testbericht verzonden.",
        ["Settings_WebhookReturnedError"] = "Webhook gaf een fout terug.",
        ["Settings_WebhookFailed"] = "Mislukt: {0}",

        // ----- Twitch model display -----
        ["Model_RemovePreferred"] = "⭐ Voorkeur verwijderen",
        ["Model_PreferChannel"] = "⭐ Dit kanaal als voorkeur",
        ["Model_RemoveAvoided"] = "\U0001F6AB Vermijding verwijderen",
        ["Model_AvoidChannel"] = "\U0001F6AB Dit kanaal vermijden",
        ["Model_ChannelLive"] = "LIVE - {0}",
        ["Model_ChannelOffline"] = "offline",
        ["Model_DropProgress"] = "{0}/{1} min",
        ["Model_DropProgressSummary"] = "{0}  ({1}/{2} min)",
        ["Model_Remaining"] = "{0} resterend",
        ["Model_Linked"] = "Gekoppeld",
        ["Model_LinkNeeded"] = "Koppeling nodig",
        ["Model_Ends"] = "Eindigt {0}",
    };
}
