namespace DropHarvester.Localization;

/// <summary>Русский (Russian) string table. Any key not present falls back to the English base.</summary>
public static partial class LocStrings
{
    public static readonly Dictionary<string, string> Ru = new(StringComparer.Ordinal)
    {
        // ----- common -----
        ["Common_Cancel"] = "Отмена",
        ["Common_Harvest"] = "Собрать",
        ["Common_Harvesting"] = "Сбор",

        // ----- tab titles -----
        ["Tab_Status"] = "Состояние",
        ["Tab_Inventory"] = "Инвентарь",
        ["Tab_Channels"] = "Каналы",
        ["Tab_Settings"] = "Настройки",
        ["Tab_Log"] = "Журнал",
        ["Tab_Stats"] = "Статистика",

        // ----- Status page -----
        ["Status_UpdateReady"] = "Обновление готово",
        ["Status_UpdateNow"] = "Обновить сейчас",
        ["Status_UpdateAvailableTitle"] = "Доступно обновление",
        ["Status_UpdateAvailableDetail"] = "Доступна версия v{0} - настоятельно рекомендуется обновить.",
        ["Status_UpdateDownloading"] = "Загрузка v{0}...",
        ["Status_Download"] = "Скачать",
        ["Status_Account"] = "АККАУНТ",
        ["Status_LogIn"] = "Войти через Twitch",
        ["Status_LogOut"] = "Выйти",
        ["Status_AuthorizeHeader"] = "АВТОРИЗУЙТЕ ЭТО ПРИЛОЖЕНИЕ",
        ["Status_AuthorizeBody"] = "Открылось окно браузера. Введите этот код, чтобы привязать свой аккаунт Twitch:",
        ["Status_Harvesting"] = "СБОР",
        ["Status_StartHarvesting"] = "Начать сбор",
        ["Status_PauseHarvesting"] = "Приостановить сбор",
        ["Status_Channel"] = "Канал",
        ["Status_Game"] = "Игра",
        ["Status_Campaign"] = "Кампания",
        ["Status_WatchLive"] = "Смотреть трансляцию",
        ["Status_CampaignProgress"] = "Прогресс кампании",
        ["Status_UpNext"] = "ДАЛЕЕ",
        ["Status_Queue"] = "ОЧЕРЕДЬ",
        ["Status_RemoveOverride"] = "Убрать переопределение",
        ["Status_Overriding"] = "Переопределение...",
        ["Changelog_ViewChanges"] = "Показать изменения",
        ["Changelog_Title"] = "Что нового",
        ["Changelog_YouAreHere"] = "ВЫ ЗДЕСЬ",
        ["Changelog_Latest"] = "ПОСЛЕДНЯЯ",
        ["Changelog_Unavailable"] = "Журнал изменений недоступен.",
        ["Status_AllowNewHigherPriority"] = "Разрешить новым кампаниям с более высоким приоритетом завершить это переопределение",

        // ----- Settings: language -----
        ["Settings_Language"] = "Язык",
        ["Settings_LanguageNav"] = "Язык",

        // ----- notifications -----
        ["Notif_NameDashGame"] = "{0} - {1}",
        ["Notif_DropClaimed"] = "Drop получен",
        ["Notif_CampaignComplete"] = "Кампания завершена",
        ["Notif_AllHarvested"] = "Все drops собраны",
        ["Notif_AllHarvestedBody"] = "Сейчас нет доступных drops для сбора.",
        ["Notif_NewDrop"] = "Доступен новый drop",
        ["Notif_LoginExpired"] = "Сессия входа истекла",
        ["Notif_LoginExpiredBody"] = "Ваша сессия Twitch истекла - пожалуйста, войдите снова.",

        // ----- Campaigns / Inventory page -----
        ["Campaigns_Refresh"] = "Обновить",
        ["Campaigns_Upcoming"] = "Предстоящие",
        ["Campaigns_Expired"] = "Истёкшие",
        ["Campaigns_NotLinked"] = "Не привязано",
        ["Campaigns_Finished"] = "Завершённые",
        ["Campaigns_Excluded"] = "Исключённые",
        ["Campaigns_Deduped"] = "Без дублей",
        ["Campaigns_SubOnly"] = "Только подписка",
        ["Campaigns_NoMatch"] = "Ни одна кампания не соответствует текущим фильтрам.",
        ["Campaigns_Harvesting"] = "Сбор",
        ["Campaigns_Claimed"] = "Получено",
        ["Campaigns_ClaimedBadge"] = "Получено",

        // ----- Channels page -----
        ["Channels_Updating"] = "Обновление...",
        ["Channels_EmptyView"] = "Пока нет отслеживаемых каналов. Сбор заполнит этот список, как только кампания станет активной.",
        ["Channels_Channel"] = "КАНАЛ",
        ["Channels_Official"] = "ОФИЦИАЛЬНЫЙ",
        ["Channels_Viewers"] = "ЗРИТЕЛИ",
        ["Channels_Status"] = "СОСТОЯНИЕ",
        ["Channels_Watch"] = "Смотреть",
        ["Channels_Switching"] = "Переключение...",
        ["Channels_Harvesting"] = "Сбор",

        // ----- Stats page -----
        ["Stats_DropsClaimed"] = "Drops получено",
        ["Stats_CampaignsDone"] = "Кампаний завершено",
        ["Stats_WatchTimeSaved"] = "Время сбора",
        ["Stats_DropsClaimedLast7Days"] = "DROPS ПОЛУЧЕНО (ЗА ПОСЛЕДНИЕ 7 ДНЕЙ)",
        ["Stats_ExportCsv"] = "Экспорт CSV",
        ["Stats_ExportJson"] = "Экспорт JSON",
        ["Stats_RecentHistory"] = "НЕДАВНЯЯ ИСТОРИЯ",
        ["Stats_NoHistoryYet"] = "История пока пуста.",

        // ----- Log page -----
        ["Log_Clear"] = "Очистить",
        ["Log_NoLogOutputYet"] = "В журнале пока нет записей.",

        // ----- Settings page -----
        ["Settings_Settings"] = "НАСТРОЙКИ",
        ["Settings_NavUpdates"] = "Обновления",
        ["Settings_NavHarvesting"] = "Сбор",
        ["Settings_NavPriorityGames"] = "Приоритетные игры",
        ["Settings_NavExcludedGames"] = "Исключённые игры",
        ["Settings_NavDedupeGames"] = "Игры без дублей",
        ["Settings_NavUnlinkedGames"] = "Непривязанные игры",
        ["Settings_NavPreferredChannels"] = "Предпочитаемые каналы",
        ["Settings_NavAvoidedChannels"] = "Избегаемые каналы",
        ["Settings_NavDropSound"] = "Звук drop",
        ["Settings_NavNotifications"] = "Уведомления",
        ["Settings_NavWebhookAlerts"] = "Оповещения через вебхуки",
        ["Settings_NavLog"] = "Журнал",
        ["Settings_NavApplication"] = "Приложение",
        ["Settings_NavDebugServer"] = "Сервер отладки",
        ["Settings_Updates"] = "ОБНОВЛЕНИЯ",
        ["Settings_AutoCheckUpdates"] = "Автоматически проверять обновления при запуске",
        ["Settings_UpdatesDescription"] = "Проверяет новую версию на GitHub при запуске и раз в день. Когда она доступна, баннер на вкладке «Статус» позволяет скачать её, а затем установить здесь или там - или она установится при следующем перезапуске.",
        ["Settings_CheckNow"] = "Проверить сейчас",
        ["Settings_UpdateNow"] = "Обновить сейчас",
        ["Settings_Harvesting"] = "СБОР",
        ["Settings_HarvestOnlyPriority"] = "Собирать только приоритетные игры",
        ["Settings_PrioritizeEndingSoonest"] = "Приоритет заканчивающимся раньше",
        ["Settings_PrioritizeEndingSoonestDescription"] = "Собирать ту подходящую кампанию, которая истекает первой - но при наличии времени всё же учитывать список приоритетов: приоритетный drop собирается раньше более срочного, если его отсрочка не приведёт к потере, а более срочный неприоритетный drop выбирается только тогда, когда это не будет стоить вам приоритетного drop.",
        ["Settings_PrioritizeByAvailability"] = "Приоритет по доступности",
        ["Settings_PrioritizeByAvailabilityDescription"] = "Только для разрешения ничьих: когда кампании в остальном равны по порядку выше, собирать первой ту, у чьей игры меньше активных стримеров с включёнными drops - забирая редкие drops, пока канал в эфире, и оставляя игры с изобилием стримов на потом. Никогда не переопределяет ваш список приоритетов.",
        ["Settings_HarvestImpossibleDrops"] = "Собирать невозможные drops",
        ["Settings_HarvestImpossibleDropsDescription"] = "Смотреть drops, которые невозможно завершить до окончания кампании (на случай её продления).",
        ["Settings_ShowUnlinkedInChannels"] = "Показывать непривязанные игры в Каналах",
        ["Settings_ShowUnlinkedInChannelsDescription"] = "По умолчанию выключено. Пропуск каналов непривязанных игр экономит запросы к каталогу (вызовы API).",
        ["Settings_IncludeBadgeEmote"] = "Включать кампании со значками/эмоциями (без привязки)",
        ["Badge_Sub"] = "ПОДПИСКА",
        ["Campaigns_BuyDrop"] = "Купить дроп",
        ["Settings_AutoClaimChannelPoints"] = "Автоматически получать баллы канала на просматриваемом канале",
        ["Settings_WhenOverridingHarvest"] = "При переопределении собирать",
        ["Settings_WhenOverridingHarvestDescription"] = "Что делает нажатие «Собрать» на кампании: всю кампанию, только её следующий drop (затем обратно в авто) или спрашивать каждый раз.",
        ["Settings_PriorityGames"] = "ПРИОРИТЕТНЫЕ ИГРЫ (ВЕРХ = ПЕРВЫМИ)",
        ["Settings_StartTypingGameName"] = "Начните вводить название игры...",
        ["Settings_Add"] = "Добавить",
        ["Settings_DragToReorder"] = "Перетаскивайте за маркер ≡ для изменения порядка (или используйте стрелки). Верх = собирается первым.",
        ["Settings_ExcludedGames"] = "ИСКЛЮЧЁННЫЕ ИГРЫ",
        ["Settings_ExcludedGamesDescription"] = "Игры из этого списка никогда не собираются - их drop-кампании полностью пропускаются, даже если игра привязана и по ней идут стримы. Используйте это, чтобы игнорировать игры, drops которых вам не нужны.",
        ["Settings_DedupeGames"] = "ИГРЫ БЕЗ ДУБЛЕЙ",
        ["Settings_DedupeGamesDescription"] = "Для добавленных сюда игр пропускать drops, награду которых вы уже получили (по истории получений Twitch за ~6 месяцев).",
        ["Settings_HarvestUnlinkedGames"] = "СОБИРАТЬ НЕПРИВЯЗАННЫЕ ИГРЫ",
        ["Settings_HarvestUnlinkedGamesDescription"] = "Собирать кампании этих игр даже без привязки аккаунта. Всегда собираются ПОСЛЕДНИМИ (ниже всех привязанных кампаний) и могут не засчитаться, если кампания в действительности требует привязки.",
        ["Settings_PreferredChannels"] = "ПРЕДПОЧИТАЕМЫЕ КАНАЛЫ (⭐)",
        ["Settings_PreferredChannelsDescription"] = "Добавьте канал ниже или щёлкните правой кнопкой по одному на вкладке Каналы. Когда предпочитаемый канал в эфире по собираемой игре и не требуется официальный канал кампании, DropHarvester простаивает на нём вместо случайного стрима с наибольшим числом зрителей - drop всё равно засчитывается, так что вы поддерживаете стримера без ущерба для сбора. Приоритет/заканчивающиеся раньше по-прежнему определяют, какая игра собирается; официальный канал всегда побеждает.",
        ["Settings_PreferredChannelPlaceholder"] = "Логин канала (например, ninja)",
        ["Settings_NoChannelsYet"] = "Пока пусто - добавьте канал выше или щелчком правой кнопки по каналу.",
        ["Settings_AvoidedChannels"] = "ИЗБЕГАЕМЫЕ КАНАЛЫ (🚫)",
        ["Settings_AvoidedChannelsDescription"] = "Добавьте канал ниже или щёлкните правой кнопкой по одному на вкладке Каналы. На избегаемом канале никогда не простаивают, если только это не единственный стрим с включёнными drops, идущий сейчас по этой игре (крайний случай).",
        ["Settings_AvoidedChannelPlaceholder"] = "Логин канала (например, somestreamer)",
        ["Settings_DropClaimedSound"] = "ЗВУК ПОЛУЧЕНИЯ DROP",
        ["Settings_PlaySoundOnDropClaimed"] = "Проигрывать звук при получении drop",
        ["Settings_Choose"] = "Выбрать...",
        ["Settings_Test"] = "Проверить",
        ["Settings_ClearSound"] = "Сбросить звук",
        ["Settings_Volume"] = "Громкость",
        ["Settings_OutputDevice"] = "Устройство вывода (Windows может использовать любое устройство; macOS использует системное по умолчанию)",
        ["Settings_DesktopNotifications"] = "УВЕДОМЛЕНИЯ НА РАБОЧЕМ СТОЛЕ",
        ["Settings_DropClaimed"] = "Drop получен",
        ["Settings_CampaignComplete"] = "Кампания завершена",
        ["Settings_AllDropsHarvested"] = "Все drops собраны",
        ["Settings_LoginExpired"] = "Сессия входа истекла",
        ["Settings_RemoteWebhookAlerts"] = "УДАЛЁННЫЕ ОПОВЕЩЕНИЯ ЧЕРЕЗ ВЕБХУКИ",
        ["Settings_EnableWebhookAlerts"] = "Включить оповещения через вебхуки",
        ["Settings_WebhookType"] = "Тип вебхука",
        ["Settings_WebhookUrl"] = "URL вебхука",
        ["Settings_SendTestMessage"] = "Отправить тестовое сообщение",
        ["Settings_SendOn"] = "ОТПРАВЛЯТЬ ПРИ",
        ["Settings_NewDropAvailable"] = "Доступен новый drop для игры",
        ["Settings_Log"] = "ЖУРНАЛ",
        ["Settings_TimestampOnEachLine"] = "Показывать метку времени на каждой строке журнала",
        ["Settings_Application"] = "ПРИЛОЖЕНИЕ",
        ["Settings_MinimizeToTray"] = "Сворачивать в трей при закрытии",
        ["Settings_StartWithSystem"] = "Запускать вместе с системой",
        ["Settings_StartMinimizedToTray"] = "Запускать свёрнутым в трей",
        ["Settings_StartMinimizedToTrayDescription"] = "Запускаться сразу в трей, а не на экране - при каждом запуске, открываете ли вы приложение сами или оно стартует вместе с системой.",
        ["Settings_ProxyOptional"] = "Прокси (необязательно)",
        ["Settings_ProxyPlaceholder"] = "http://host:port",
        ["Settings_DebugServer"] = "СЕРВЕР ОТЛАДКИ",
        ["Settings_RunLocalDebugServer"] = "Запускать локальный сервер отладки",
        ["Settings_RunLocalDebugServerDescription"] = "Предоставляет актуальное состояние и каждое решение о сборе/пропуске/получении в виде JSON на localhost - для диагностики того, что приложение делает под капотом.",
        ["Settings_Port"] = "Порт",

        // ----- engine status + common log lines -----
        ["Status_Starting"] = "Запуск...",
        ["Status_Stopped"] = "Остановлено",
        ["Status_NoDropsToHarvest"] = "Нет drops для сбора",
        ["Status_WaitingForStream"] = "Drops доступны - ожидание выхода стрима в эфир",
        ["Status_WatchingChannelGame"] = "Просмотр {0} - {1}",
        ["Status_ChannelWentOffline"] = "{0} ушёл в офлайн",
        ["Log_HarvestingStarted"] = "Сбор начат.",
        ["Log_HarvestingStopped"] = "Сбор остановлен.",
        ["Log_ConnectionReestablished"] = "Соединение восстановлено - сбор возобновляется.",
        ["Log_ConnectionLost"] = "Похоже, Twitch Drops недоступны или соединение потеряно - сбор приостановлен; возобновится автоматически, как только всё восстановится.",

        // ----- Status/login view-model strings -----
        ["Status_Idle"] = "Простой",
        ["Status_NotLoggedIn"] = "Вход не выполнен",
        ["Status_LoggedInAs"] = "Выполнен вход как {0} (id {1})",
        ["Status_ConnectionIssue"] = "Twitch Drops испытывают проблемы или вы потеряли соединение. Мы автоматически возобновим сбор, как только соединение будет восстановлено.",
        ["Status_DropsOutage"] = "Twitch принимает просмотры, но сейчас не засчитывает прогресс дропов (сбой на стороне Twitch). Сбор продолжается и автоматически возобновится, как только всё восстановят.",
        ["Login_Requesting"] = "Запрос кода входа у Twitch...",
        ["Login_GoToAndEnter"] = "Перейдите на {0} и введите код {1}",
        ["Login_NotCompleted"] = "Вход не был завершён. Пожалуйста, попробуйте снова.",
        ["Login_Cancelled"] = "Вход отменён.",
        ["Login_Failed"] = "Ошибка входа: {0}",
        ["Login_Expired"] = "Ваша сессия Twitch истекла - пожалуйста, войдите снова.",
        ["Override_HarvestPrompt"] = "Переопределение - собрать:",
        ["Override_JustNextDrop"] = "Только следующий drop",
        ["Override_EntireCampaign"] = "Всю кампанию",
        ["Override_AskEachTime"] = "Спрашивать каждый раз",

        // ----- Inventory load status -----
        ["Inventory_LoadingDrops"] = "Загрузка drops... {0}/{1}",
        ["Inventory_Loaded"] = "Кампаний: {0}.",
        ["Inventory_None"] = "Кампании не найдены.",
        ["Inventory_LoadFailed"] = "Не удалось загрузить: {0}",

        // ----- Channels view-model -----
        ["Channels_CountText"] = "{0} активных каналов по {1} играм",
        ["Channels_UnknownGame"] = "Неизвестно",
        ["Channels_OneLive"] = "1 в эфире",
        ["Channels_NLive"] = "{0} в эфире",

        // ----- Campaigns view-model -----
        ["Campaigns_ListView"] = "Список",
        ["Campaigns_GridView"] = "Сетка",
        ["Inventory_LogInFirst"] = "Сначала войдите, чтобы увидеть свой инвентарь.",
        ["Inventory_LoadingCampaigns"] = "Загрузка кампаний...",

        // ----- Stats view-model -----
        ["Stats_ExportedJson"] = "JSON экспортирован в {0}",
        ["Stats_ExportedCsv"] = "CSV экспортирован в {0}",
        ["Stats_Since"] = "С {0}",

        // ----- Log view-model -----
        ["Log_Copy"] = "Копировать",
        ["Log_Copied"] = "Скопировано!",
        ["Log_CopyFailed"] = "Не удалось скопировать",

        // ----- Settings view-model -----
        ["Settings_NoSoundChosen"] = "Звук не выбран",
        ["Settings_ChooseSoundTitle"] = "Выберите звук для проигрывания при получении drop",
        ["Settings_SoundPickFailed"] = "Не удалось выбрать файл: {0}",
        ["Settings_AudioNotAvailable"] = "Воспроизведение звука недоступно на этой платформе.",
        ["Settings_ChooseSoundFirst"] = "Сначала выберите звуковой файл.",
        ["Settings_SystemDefault"] = "Системное по умолчанию",
        ["Settings_PlayingOn"] = "Воспроизведение на {0} с громкостью {1}...",
        ["Settings_InvalidGameHint"] = "Недопустимая игра Twitch - выберите из подсказок.",
        ["Settings_TimestampDate"] = "Дата",
        ["Settings_TimestampTime"] = "Время",
        ["Settings_TimestampDateAndTime"] = "Дата и время",
        ["Settings_TimestampTimeAndDate"] = "Время и дата",
        ["Settings_Clock12Hour"] = "12-часовой формат",
        ["Settings_Clock24Hour"] = "24-часовой формат",
        ["Settings_CurrentVersion"] = "У вас версия v{0}.",
        ["Settings_UpdateReadyStatus"] = "Обновление v{0} готово - нажмите «Обновить сейчас» для установки.",
        ["Settings_CheckingForUpdates"] = "Проверка обновлений...",
        ["Settings_UpdateServerUnreachable"] = "Не удалось связаться с сервером обновлений.",
        ["Settings_OnLatestVersion"] = "У вас последняя версия (v{0}).",
        ["Settings_DownloadingUpdate"] = "Загрузка обновления v{0}...",
        ["Settings_UpdateReadyAutoInstall"] = "Обновление v{0} готово - нажмите «Обновить сейчас» для установки или оно установится автоматически при следующем перезапуске.",
        ["Settings_UpdateDownloadFailed"] = "Не удалось загрузить обновление - попробуйте снова.",
        ["Settings_UpdateCheckFailed"] = "Не удалось проверить обновления.",
        ["Settings_InstallingUpdate"] = "Установка обновления - приложение перезапустится...",
        ["Settings_InstallerStartFailed"] = "Не удалось запустить установщик - оно установится автоматически при следующем перезапуске.",
        ["Settings_DebugServerRunning"] = "Работает - откройте {0} (только localhost)",
        ["Settings_DebugServerOff"] = "Выключено",
        ["Settings_Hide"] = "Скрыть",
        ["Settings_Show"] = "Показать",
        ["Settings_WebhookGeneric"] = "Обычный",
        ["Settings_Sending"] = "Отправка...",
        ["Settings_WebhookEnterUrlFirst"] = "Сначала введите URL вебхука.",
        ["Settings_WebhookTestSent"] = "Тестовое сообщение отправлено.",
        ["Settings_WebhookReturnedError"] = "Вебхук вернул ошибку.",
        ["Settings_WebhookFailed"] = "Ошибка: {0}",

        // ----- Twitch model display -----
        ["Model_RemovePreferred"] = "⭐ Убрать из предпочитаемых",
        ["Model_PreferChannel"] = "⭐ Предпочитать этот канал",
        ["Model_RemoveAvoided"] = "\U0001F6AB Убрать из избегаемых",
        ["Model_AvoidChannel"] = "\U0001F6AB Избегать этот канал",
        ["Model_ChannelLive"] = "В ЭФИРЕ - {0}",
        ["Model_ChannelOffline"] = "офлайн",
        ["Model_DropProgress"] = "{0}/{1} мин",
        ["Model_DropProgressSummary"] = "{0}  ({1}/{2} мин)",
        ["Model_Remaining"] = "осталось {0}",
        ["Model_Linked"] = "Привязано",
        ["Model_LinkNeeded"] = "Требуется привязка",
        ["Model_Ends"] = "Завершается {0}",
    };
}
