namespace DropHarvester.Localization;

/// <summary>日本語 (Japanese) string table. Any key not present falls back to the English base.</summary>
public static partial class LocStrings
{
    public static readonly Dictionary<string, string> Ja = new(StringComparer.Ordinal)
    {
        // ----- common -----
        ["Common_Cancel"] = "キャンセル",
        ["Common_Harvest"] = "収集",
        ["Common_Harvesting"] = "収集中",

        // ----- tab titles -----
        ["Tab_Status"] = "ステータス",
        ["Tab_Inventory"] = "インベントリ",
        ["Tab_Channels"] = "チャンネル",
        ["Tab_Settings"] = "設定",
        ["Tab_Log"] = "ログ",
        ["Tab_Stats"] = "統計",

        // ----- Status page -----
        ["Status_UpdateReady"] = "アップデートの準備完了",
        ["Status_UpdateNow"] = "今すぐアップデート",
        ["Status_UpdateAvailableTitle"] = "アップデートが利用可能",
        ["Status_UpdateAvailableDetail"] = "バージョン v{0} が利用可能です - アップデートを強くお勧めします。",
        ["Status_UpdateDownloading"] = "v{0} をダウンロード中...",
        ["Status_Download"] = "ダウンロード",
        ["Status_Account"] = "アカウント",
        ["Status_LogIn"] = "Twitch でログイン",
        ["Status_LogOut"] = "ログアウト",
        ["Status_AuthorizeHeader"] = "このアプリを認証",
        ["Status_AuthorizeBody"] = "ブラウザーのウィンドウが開きました。このコードを入力して Twitch アカウントを連携してください:",
        ["Status_Harvesting"] = "収集中",
        ["Status_StartHarvesting"] = "収集を開始",
        ["Status_PauseHarvesting"] = "収集を一時停止",
        ["Status_Channel"] = "チャンネル",
        ["Status_Game"] = "ゲーム",
        ["Status_Campaign"] = "キャンペーン",
        ["Status_CampaignProgress"] = "キャンペーンの進捗",
        ["Status_UpNext"] = "次の予定",
        ["Status_Queue"] = "キュー",
        ["Status_RemoveOverride"] = "上書きを解除",
        ["Status_AllowNewHigherPriority"] = "より優先度の高い新しいキャンペーンでこの上書きを終了できるようにする",

        // ----- Settings: language -----
        ["Settings_Language"] = "言語",
        ["Settings_LanguageNav"] = "言語",

        // ----- notifications -----
        ["Notif_NameDashGame"] = "{0} - {1}",
        ["Notif_DropClaimed"] = "Drops を受け取りました",
        ["Notif_CampaignComplete"] = "キャンペーン完了",
        ["Notif_AllHarvested"] = "すべての Drops を収集しました",
        ["Notif_AllHarvestedBody"] = "現在、収集できる Drops はこれ以上ありません。",
        ["Notif_NewDrop"] = "新しい Drops が利用可能",
        ["Notif_LoginExpired"] = "ログインの有効期限切れ",
        ["Notif_LoginExpiredBody"] = "Twitch のセッションが期限切れになりました - もう一度ログインしてください。",

        // ----- Campaigns / Inventory page -----
        ["Campaigns_Refresh"] = "更新",
        ["Campaigns_Upcoming"] = "開始予定",
        ["Campaigns_Expired"] = "期限切れ",
        ["Campaigns_NotLinked"] = "未連携",
        ["Campaigns_Finished"] = "完了",
        ["Campaigns_Excluded"] = "除外済み",
        ["Campaigns_Deduped"] = "重複除去済み",
        ["Campaigns_NoMatch"] = "現在のフィルターに一致するキャンペーンはありません。",
        ["Campaigns_Harvesting"] = "収集中",
        ["Campaigns_Claimed"] = "受取済み",
        ["Campaigns_ClaimedBadge"] = "受取済み",

        // ----- Channels page -----
        ["Channels_Updating"] = "更新中...",
        ["Channels_EmptyView"] = "まだ追跡中のチャンネルはありません。キャンペーンが有効になると収集によってここに表示されます。",
        ["Channels_Channel"] = "チャンネル",
        ["Channels_Official"] = "公式",
        ["Channels_Viewers"] = "視聴者数",
        ["Channels_Status"] = "ステータス",
        ["Channels_Watch"] = "視聴",
        ["Channels_Switching"] = "切り替え中...",
        ["Channels_Harvesting"] = "収集中",

        // ----- Stats page -----
        ["Stats_DropsClaimed"] = "受け取った Drops",
        ["Stats_CampaignsDone"] = "完了したキャンペーン",
        ["Stats_WatchTimeSaved"] = "収穫に費やした時間",
        ["Stats_DropsClaimedLast7Days"] = "受け取った Drops (過去 7 日間)",
        ["Stats_ExportCsv"] = "CSV をエクスポート",
        ["Stats_ExportJson"] = "JSON をエクスポート",
        ["Stats_RecentHistory"] = "最近の履歴",
        ["Stats_NoHistoryYet"] = "まだ履歴はありません。",

        // ----- Log page -----
        ["Log_Clear"] = "クリア",
        ["Log_NoLogOutputYet"] = "まだログ出力はありません。",

        // ----- Settings page -----
        ["Settings_Settings"] = "設定",
        ["Settings_NavUpdates"] = "アップデート",
        ["Settings_NavHarvesting"] = "収集",
        ["Settings_NavPriorityGames"] = "優先ゲーム",
        ["Settings_NavExcludedGames"] = "除外ゲーム",
        ["Settings_NavDedupeGames"] = "重複除去ゲーム",
        ["Settings_NavUnlinkedGames"] = "未連携ゲーム",
        ["Settings_NavPreferredChannels"] = "優先チャンネル",
        ["Settings_NavAvoidedChannels"] = "回避チャンネル",
        ["Settings_NavDropSound"] = "Drop サウンド",
        ["Settings_NavNotifications"] = "通知",
        ["Settings_NavWebhookAlerts"] = "Webhook アラート",
        ["Settings_NavLog"] = "ログ",
        ["Settings_NavApplication"] = "アプリケーション",
        ["Settings_NavDebugServer"] = "デバッグサーバー",
        ["Settings_Updates"] = "アップデート",
        ["Settings_AutoCheckUpdates"] = "起動時に自動でアップデートを確認する",
        ["Settings_UpdatesDescription"] = "起動時および1日1回、GitHub で新しいバージョンを確認します。利用可能な場合は、ステータスタブのバナーからダウンロードし、ここまたはそこでインストールできます。次回の再起動時に自動インストールもされます。",
        ["Settings_CheckNow"] = "今すぐ確認",
        ["Settings_UpdateNow"] = "今すぐアップデート",
        ["Settings_Harvesting"] = "収集",
        ["Settings_HarvestOnlyPriority"] = "優先ゲームのみ収集する",
        ["Settings_PrioritizeEndingSoonest"] = "終了が近い順に優先する",
        ["Settings_PrioritizeEndingSoonestDescription"] = "対象となるキャンペーンのうち、最も早く期限切れになるものを収集します - ただし時間に余裕がある場合は優先リストを尊重します。優先 Drop を先送りしても失わずに済む場合は、より早く終わるものより先に優先 Drop を収集し、より早く終わる非優先 Drop は、それによって優先 Drop を逃さない場合にのみ選ばれます。",
        ["Settings_PrioritizeByAvailability"] = "入手性で優先する",
        ["Settings_PrioritizeByAvailabilityDescription"] = "タイブレークのみ: 上記の順序でキャンペーンが同順位の場合、そのゲームで Drops 対応のライブ配信者が少ないものを先に収集します - チャンネルがライブ中に希少な配信の Drops を確保し、配信の多いゲームは後回しにします。優先リストを上書きすることはありません。",
        ["Settings_HarvestImpossibleDrops"] = "達成不可能な Drops も収集する",
        ["Settings_HarvestImpossibleDropsDescription"] = "キャンペーン終了までに完了できない Drops も視聴します (延長される場合に備えて)。",
        ["Settings_ShowUnlinkedInChannels"] = "未連携ゲームを「チャンネル」に表示する",
        ["Settings_ShowUnlinkedInChannelsDescription"] = "デフォルトはオフです。未連携ゲームのチャンネルをスキップするとディレクトリ検索 (API 呼び出し) を節約できます。",
        ["Settings_IncludeBadgeEmote"] = "バッジ/エモートのキャンペーンを含める (連携不要)",
        ["Settings_AutoClaimChannelPoints"] = "視聴中のチャンネルでチャンネルポイントを自動受け取りする",
        ["Settings_WhenOverridingHarvest"] = "上書き時に収集する対象",
        ["Settings_WhenOverridingHarvestDescription"] = "キャンペーンで「収集」をクリックしたときの動作: キャンペーン全体、次の Drop だけ (その後は自動に戻る)、または毎回確認する。",
        ["Settings_PriorityGames"] = "優先ゲーム (上が最優先)",
        ["Settings_StartTypingGameName"] = "ゲーム名を入力し始めてください...",
        ["Settings_Add"] = "追加",
        ["Settings_DragToReorder"] = "≡ ハンドルをドラッグして並べ替えます (または矢印を使用)。上が先に収集されます。",
        ["Settings_ExcludedGames"] = "除外ゲーム",
        ["Settings_ExcludedGamesDescription"] = "このリストのゲームは決して収集されません - ゲームが連携済みでライブ配信があっても、その Drop キャンペーンは完全にスキップされます。Drops が不要なゲームを無視するのに使用します。",
        ["Settings_DedupeGames"] = "重複除去ゲーム",
        ["Settings_DedupeGamesDescription"] = "ここに追加したゲームでは、すでに所有している報酬の Drops を (Twitch の約 6 か月分の受け取り履歴から) スキップします。",
        ["Settings_HarvestUnlinkedGames"] = "未連携ゲームを収集",
        ["Settings_HarvestUnlinkedGamesDescription"] = "これらのゲームのキャンペーンをアカウント連携なしでも収集します。常に最後に収集され (連携済みのすべてのキャンペーンの下)、キャンペーンが実際に連携を必要とする場合は付与されないことがあります。",
        ["Settings_PreferredChannels"] = "優先チャンネル (⭐)",
        ["Settings_PreferredChannelsDescription"] = "下にチャンネルを追加するか、「チャンネル」タブでチャンネルを右クリックしてください。優先チャンネルが収集対象のゲームでライブ中で、公式キャンペーンチャンネルが必須でない場合、DropHarvester はランダムな上位視聴者の配信ではなくそのチャンネルで待機します - Drop は引き続き付与されるので、収集を損なうことなく配信者を応援できます。どのゲームを収集するかは優先度/終了が近い順で決まり、公式チャンネルが常に優先されます。",
        ["Settings_PreferredChannelPlaceholder"] = "チャンネルのログイン名 (例: ninja)",
        ["Settings_NoChannelsYet"] = "まだありません - 上で追加するか、チャンネルを右クリックしてください。",
        ["Settings_AvoidedChannels"] = "回避チャンネル (🚫)",
        ["Settings_AvoidedChannelsDescription"] = "下にチャンネルを追加するか、「チャンネル」タブでチャンネルを右クリックしてください。回避チャンネルは、現在そのゲームでライブ中の Drops 対応配信がそれだけになった場合 (最終手段) を除き、決して待機に使われません。",
        ["Settings_AvoidedChannelPlaceholder"] = "チャンネルのログイン名 (例: somestreamer)",
        ["Settings_DropClaimedSound"] = "Drop 受け取りサウンド",
        ["Settings_PlaySoundOnDropClaimed"] = "Drop を受け取ったときにサウンドを再生する",
        ["Settings_Choose"] = "選択...",
        ["Settings_Test"] = "テスト",
        ["Settings_ClearSound"] = "サウンドをクリア",
        ["Settings_Volume"] = "音量",
        ["Settings_OutputDevice"] = "出力デバイス (Windows は任意のデバイスを指定可能。macOS はシステムの既定を使用)",
        ["Settings_DesktopNotifications"] = "デスクトップ通知",
        ["Settings_DropClaimed"] = "Drops を受け取りました",
        ["Settings_CampaignComplete"] = "キャンペーン完了",
        ["Settings_AllDropsHarvested"] = "すべての Drops を収集しました",
        ["Settings_LoginExpired"] = "ログインの有効期限切れ",
        ["Settings_RemoteWebhookAlerts"] = "リモート Webhook アラート",
        ["Settings_EnableWebhookAlerts"] = "Webhook アラートを有効にする",
        ["Settings_WebhookType"] = "Webhook の種類",
        ["Settings_WebhookUrl"] = "Webhook URL",
        ["Settings_SendTestMessage"] = "テストメッセージを送信",
        ["Settings_SendOn"] = "送信するタイミング",
        ["Settings_NewDropAvailable"] = "ゲームの新しい Drop が利用可能",
        ["Settings_Log"] = "ログ",
        ["Settings_TimestampOnEachLine"] = "各ログ行にタイムスタンプを表示する",
        ["Settings_Application"] = "アプリケーション",
        ["Settings_MinimizeToTray"] = "閉じるときにトレイに最小化する",
        ["Settings_StartWithSystem"] = "システムと共に起動する",
        ["Settings_StartMinimizedToTray"] = "トレイに最小化した状態で起動する",
        ["Settings_StartMinimizedToTrayDescription"] = "画面に表示せず、直接トレイに起動します - 自分で開いた場合もシステムと共に起動した場合も、毎回同様です。",
        ["Settings_ProxyOptional"] = "プロキシ (任意)",
        ["Settings_ProxyPlaceholder"] = "http://host:port",
        ["Settings_DebugServer"] = "デバッグサーバー",
        ["Settings_RunLocalDebugServer"] = "ローカルデバッグサーバーを実行する",
        ["Settings_RunLocalDebugServerDescription"] = "ライブの状態と、すべての収集/スキップ/受け取りの判断を localhost 上で JSON として公開します - アプリが内部で何をしているかを診断するためのものです。",
        ["Settings_Port"] = "ポート",

        // ----- engine status + common log lines -----
        ["Status_Starting"] = "起動中...",
        ["Status_Stopped"] = "停止しました",
        ["Status_NoDropsToHarvest"] = "収集する Drops がありません",
        ["Status_WaitingForStream"] = "Drops が利用可能 - 配信が開始されるのを待っています",
        ["Status_WatchingChannelGame"] = "視聴中 {0} - {1}",
        ["Status_ChannelWentOffline"] = "{0} がオフラインになりました",
        ["Log_HarvestingStarted"] = "収集を開始しました。",
        ["Log_HarvestingStopped"] = "収集を停止しました。",
        ["Log_ConnectionReestablished"] = "接続が再確立されました - 収集を再開します。",
        ["Log_ConnectionLost"] = "Twitch Drops がダウンしているか、接続が失われたようです - 収集を一時停止しました。復旧次第、自動で再開します。",

        // ----- Status/login view-model strings -----
        ["Status_Idle"] = "待機中",
        ["Status_NotLoggedIn"] = "ログインしていません",
        ["Status_LoggedInAs"] = "{0} としてログイン中 (id {1})",
        ["Status_ConnectionIssue"] = "Twitch Drops に問題が発生しているか、接続が失われました。接続が再確立され次第、自動で収集を再開します。",
        ["Login_Requesting"] = "Twitch にログインコードを要求しています...",
        ["Login_GoToAndEnter"] = "{0} にアクセスしてコード {1} を入力してください",
        ["Login_NotCompleted"] = "ログインが完了しませんでした。もう一度お試しください。",
        ["Login_Cancelled"] = "ログインをキャンセルしました。",
        ["Login_Failed"] = "ログインに失敗しました: {0}",
        ["Login_Expired"] = "Twitch のセッションが期限切れになりました - もう一度ログインしてください。",
        ["Override_HarvestPrompt"] = "上書き - 収集する対象:",
        ["Override_JustNextDrop"] = "次の Drop だけ",
        ["Override_EntireCampaign"] = "キャンペーン全体",
        ["Override_AskEachTime"] = "毎回確認する",

        // ----- Inventory load status -----
        ["Inventory_LoadingDrops"] = "Drops を読み込み中... {0}/{1}",
        ["Inventory_Loaded"] = "{0} 件のキャンペーン。",
        ["Inventory_None"] = "キャンペーンが見つかりませんでした。",
        ["Inventory_LoadFailed"] = "読み込みに失敗しました: {0}",

        // ----- Channels view-model -----
        ["Channels_CountText"] = "{1} ゲームにわたって {0} のライブチャンネル",
        ["Channels_UnknownGame"] = "不明",
        ["Channels_OneLive"] = "1 件ライブ",
        ["Channels_NLive"] = "{0} 件ライブ",

        // ----- Campaigns view-model -----
        ["Campaigns_ListView"] = "リスト表示",
        ["Campaigns_GridView"] = "グリッド表示",
        ["Inventory_LogInFirst"] = "インベントリを表示するには、まずログインしてください。",
        ["Inventory_LoadingCampaigns"] = "キャンペーンを読み込み中...",

        // ----- Stats view-model -----
        ["Stats_ExportedJson"] = "JSON を {0} にエクスポートしました",
        ["Stats_ExportedCsv"] = "CSV を {0} にエクスポートしました",
        ["Stats_Since"] = "{0} 以降",

        // ----- Log view-model -----
        ["Log_Copy"] = "コピー",
        ["Log_Copied"] = "コピーしました!",
        ["Log_CopyFailed"] = "コピーに失敗しました",

        // ----- Settings view-model -----
        ["Settings_NoSoundChosen"] = "サウンドが選択されていません",
        ["Settings_ChooseSoundTitle"] = "Drop を受け取ったときに再生するサウンドを選択",
        ["Settings_SoundPickFailed"] = "ファイルを選択できませんでした: {0}",
        ["Settings_AudioNotAvailable"] = "このプラットフォームではオーディオの再生を利用できません。",
        ["Settings_ChooseSoundFirst"] = "まずサウンドファイルを選択してください。",
        ["Settings_SystemDefault"] = "システムの既定",
        ["Settings_PlayingOn"] = "{0} で {1} の音量で再生中...",
        ["Settings_InvalidGameHint"] = "有効な Twitch のゲームではありません - 候補から選択してください。",
        ["Settings_TimestampDate"] = "日付",
        ["Settings_TimestampTime"] = "時刻",
        ["Settings_TimestampDateAndTime"] = "日付と時刻",
        ["Settings_TimestampTimeAndDate"] = "時刻と日付",
        ["Settings_Clock12Hour"] = "12 時間表示",
        ["Settings_Clock24Hour"] = "24 時間表示",
        ["Settings_CurrentVersion"] = "現在のバージョンは v{0} です。",
        ["Settings_UpdateReadyStatus"] = "アップデート v{0} の準備が完了しました - 「今すぐアップデート」をクリックしてインストールしてください。",
        ["Settings_CheckingForUpdates"] = "アップデートを確認中...",
        ["Settings_UpdateServerUnreachable"] = "アップデートサーバーに接続できませんでした。",
        ["Settings_OnLatestVersion"] = "最新バージョン (v{0}) を使用しています。",
        ["Settings_DownloadingUpdate"] = "アップデート v{0} をダウンロード中...",
        ["Settings_UpdateReadyAutoInstall"] = "アップデート v{0} の準備が完了しました - 「今すぐアップデート」をクリックしてインストールするか、次回の再起動時に自動でインストールされます。",
        ["Settings_UpdateDownloadFailed"] = "アップデートのダウンロードに失敗しました - もう一度お試しください。",
        ["Settings_UpdateCheckFailed"] = "アップデートの確認に失敗しました。",
        ["Settings_InstallingUpdate"] = "アップデートをインストール中 - アプリが再起動します...",
        ["Settings_InstallerStartFailed"] = "インストーラーを起動できませんでした - 次回の再起動時に自動でインストールされます。",
        ["Settings_DebugServerRunning"] = "実行中 - {0} を開く (localhost のみ)",
        ["Settings_DebugServerOff"] = "オフ",
        ["Settings_Hide"] = "非表示",
        ["Settings_Show"] = "表示",
        ["Settings_WebhookGeneric"] = "汎用",
        ["Settings_Sending"] = "送信中...",
        ["Settings_WebhookEnterUrlFirst"] = "まず Webhook URL を入力してください。",
        ["Settings_WebhookTestSent"] = "テストメッセージを送信しました。",
        ["Settings_WebhookReturnedError"] = "Webhook がエラーを返しました。",
        ["Settings_WebhookFailed"] = "失敗しました: {0}",

        // ----- Twitch model display -----
        ["Model_RemovePreferred"] = "⭐ 優先を解除",
        ["Model_PreferChannel"] = "⭐ このチャンネルを優先",
        ["Model_RemoveAvoided"] = "\U0001F6AB 回避を解除",
        ["Model_AvoidChannel"] = "\U0001F6AB このチャンネルを回避",
        ["Model_ChannelLive"] = "ライブ - {0}",
        ["Model_ChannelOffline"] = "オフライン",
        ["Model_DropProgress"] = "{0}/{1} 分",
        ["Model_DropProgressSummary"] = "{0}  ({1}/{2} 分)",
        ["Model_Remaining"] = "残り {0}",
        ["Model_Linked"] = "連携済み",
        ["Model_LinkNeeded"] = "連携が必要",
        ["Model_Ends"] = "終了 {0}",
    };
}
