namespace DropHarvester.Localization;

/// <summary>Français (French) string table. Any key not present falls back to the English base.</summary>
public static partial class LocStrings
{
    public static readonly Dictionary<string, string> Fr = new(StringComparer.Ordinal)
    {
        // ----- common -----
        ["Common_Cancel"] = "Annuler",
        ["Common_Harvest"] = "Récolter",
        ["Common_Harvesting"] = "Récolte en cours",

        // ----- tab titles -----
        ["Tab_Status"] = "État",
        ["Tab_Inventory"] = "Inventaire",
        ["Tab_Channels"] = "Chaînes",
        ["Tab_Settings"] = "Paramètres",
        ["Tab_Log"] = "Journal",
        ["Tab_Stats"] = "Statistiques",

        // ----- Status page -----
        ["Status_UpdateReady"] = "Mise à jour prête",
        ["Status_UpdateNow"] = "Mettre à jour maintenant",
        ["Status_UpdateAvailableTitle"] = "Mise à jour disponible",
        ["Status_UpdateAvailableDetail"] = "La version v{0} est disponible - il est fortement recommandé de mettre à jour.",
        ["Status_UpdateDownloading"] = "Téléchargement de v{0}...",
        ["Status_Download"] = "Télécharger",
        ["Status_Account"] = "COMPTE",
        ["Status_LogIn"] = "Se connecter avec Twitch",
        ["Status_LogOut"] = "Se déconnecter",
        ["Status_AuthorizeHeader"] = "AUTORISER CETTE APPLICATION",
        ["Status_AuthorizeBody"] = "Une fenêtre de navigateur a été ouverte. Saisissez ce code pour lier votre compte Twitch :",
        ["Status_Harvesting"] = "RÉCOLTE",
        ["Status_StartHarvesting"] = "Démarrer la récolte",
        ["Status_PauseHarvesting"] = "Mettre la récolte en pause",
        ["Status_Channel"] = "Chaîne",
        ["Status_Game"] = "Jeu",
        ["Status_Campaign"] = "Campagne",
        ["Status_WatchLive"] = "Regarder en direct",
        ["Status_CampaignProgress"] = "Progression de la campagne",
        ["Status_UpNext"] = "À SUIVRE",
        ["Status_Queue"] = "FILE D'ATTENTE",
        ["Status_RemoveOverride"] = "Supprimer le forçage",
        ["Status_AllowNewHigherPriority"] = "Autoriser les nouvelles campagnes plus prioritaires à mettre fin à ce forçage",

        // ----- Settings: language -----
        ["Settings_Language"] = "Langue",
        ["Settings_LanguageNav"] = "Langue",

        // ----- notifications -----
        ["Notif_NameDashGame"] = "{0} - {1}",
        ["Notif_DropClaimed"] = "Drop réclamé",
        ["Notif_CampaignComplete"] = "Campagne terminée",
        ["Notif_AllHarvested"] = "Tous les drops récoltés",
        ["Notif_AllHarvestedBody"] = "Aucun autre drop disponible à récolter pour le moment.",
        ["Notif_NewDrop"] = "Nouveau drop disponible",
        ["Notif_LoginExpired"] = "Session expirée",
        ["Notif_LoginExpiredBody"] = "Votre session Twitch a expiré - veuillez vous reconnecter.",

        // ----- Campaigns / Inventory page -----
        ["Campaigns_Refresh"] = "Actualiser",
        ["Campaigns_Upcoming"] = "À venir",
        ["Campaigns_Expired"] = "Expirées",
        ["Campaigns_NotLinked"] = "Non liées",
        ["Campaigns_Finished"] = "Terminées",
        ["Campaigns_Excluded"] = "Exclues",
        ["Campaigns_Deduped"] = "Dédupliquées",
        ["Campaigns_NoMatch"] = "Aucune campagne ne correspond aux filtres actuels.",
        ["Campaigns_Harvesting"] = "Récolte en cours",
        ["Campaigns_Claimed"] = "Réclamées",
        ["Campaigns_ClaimedBadge"] = "Réclamé",

        // ----- Channels page -----
        ["Channels_Updating"] = "Mise à jour...",
        ["Channels_EmptyView"] = "Aucune chaîne suivie pour l'instant. La récolte remplit cette liste dès qu'une campagne est active.",
        ["Channels_Channel"] = "CHAÎNE",
        ["Channels_Official"] = "OFFICIELLE",
        ["Channels_Viewers"] = "SPECTATEURS",
        ["Channels_Status"] = "ÉTAT",
        ["Channels_Watch"] = "Regarder",
        ["Channels_Switching"] = "Changement...",
        ["Channels_Harvesting"] = "Récolte en cours",

        // ----- Stats page -----
        ["Stats_DropsClaimed"] = "Drops réclamés",
        ["Stats_CampaignsDone"] = "Campagnes terminées",
        ["Stats_WatchTimeSaved"] = "Temps passé à récolter",
        ["Stats_DropsClaimedLast7Days"] = "DROPS RÉCLAMÉS (7 DERNIERS JOURS)",
        ["Stats_ExportCsv"] = "Exporter en CSV",
        ["Stats_ExportJson"] = "Exporter en JSON",
        ["Stats_RecentHistory"] = "HISTORIQUE RÉCENT",
        ["Stats_NoHistoryYet"] = "Pas encore d'historique.",

        // ----- Log page -----
        ["Log_Clear"] = "Effacer",
        ["Log_NoLogOutputYet"] = "Aucune sortie de journal pour l'instant.",

        // ----- Settings page -----
        ["Settings_Settings"] = "PARAMÈTRES",
        ["Settings_NavUpdates"] = "Mises à jour",
        ["Settings_NavHarvesting"] = "Récolte",
        ["Settings_NavPriorityGames"] = "Jeux prioritaires",
        ["Settings_NavExcludedGames"] = "Jeux exclus",
        ["Settings_NavDedupeGames"] = "Déduplication des jeux",
        ["Settings_NavUnlinkedGames"] = "Jeux non liés",
        ["Settings_NavPreferredChannels"] = "Chaînes préférées",
        ["Settings_NavAvoidedChannels"] = "Chaînes évitées",
        ["Settings_NavDropSound"] = "Son de drop",
        ["Settings_NavNotifications"] = "Notifications",
        ["Settings_NavWebhookAlerts"] = "Alertes webhook",
        ["Settings_NavLog"] = "Journal",
        ["Settings_NavApplication"] = "Application",
        ["Settings_NavDebugServer"] = "Serveur de débogage",
        ["Settings_Updates"] = "MISES À JOUR",
        ["Settings_AutoCheckUpdates"] = "Rechercher automatiquement les mises à jour au démarrage",
        ["Settings_UpdatesDescription"] = "Recherche une nouvelle version sur GitHub au démarrage et une fois par jour. Quand une est disponible, une bannière dans l'onglet Statut permet de la télécharger, puis de l'installer ici ou là - ou elle s'installe au prochain redémarrage.",
        ["Settings_CheckNow"] = "Rechercher maintenant",
        ["Settings_UpdateNow"] = "Mettre à jour maintenant",
        ["Settings_Harvesting"] = "RÉCOLTE",
        ["Settings_HarvestOnlyPriority"] = "Récolter uniquement les jeux prioritaires",
        ["Settings_PrioritizeEndingSoonest"] = "Prioriser celles qui expirent le plus tôt",
        ["Settings_PrioritizeEndingSoonestDescription"] = "Récolter la campagne éligible qui expire en premier - tout en respectant la liste de priorités quand le temps le permet : un drop prioritaire est récolté avant un drop qui se termine plus tôt chaque fois que le reporter ne le ferait pas perdre, et un drop non prioritaire qui se termine plus tôt n'est choisi que s'il ne vous coûte pas un drop prioritaire.",
        ["Settings_PrioritizeByAvailability"] = "Prioriser par disponibilité",
        ["Settings_PrioritizeByAvailabilityDescription"] = "Départage uniquement : lorsque des campagnes sont à égalité selon l'ordre ci-dessus, récolter en premier celle dont le jeu compte le moins de streamers en direct avec drops activés - saisir les drops de streams rares tant qu'une chaîne est en direct et laisser attendre les jeux abondants. Ne prime jamais sur votre liste de priorités.",
        ["Settings_HarvestImpossibleDrops"] = "Récolter les drops impossibles",
        ["Settings_HarvestImpossibleDropsDescription"] = "Regarder les drops qui ne peuvent pas se terminer avant la fin de la campagne (au cas où elle serait prolongée).",
        ["Settings_ShowUnlinkedInChannels"] = "Afficher les jeux non liés dans Chaînes",
        ["Settings_ShowUnlinkedInChannelsDescription"] = "Désactivé par défaut. Ignorer les chaînes des jeux non liés économise des recherches d'annuaire (appels API).",
        ["Settings_IncludeBadgeEmote"] = "Inclure les campagnes de badge/emote (sans lien)",
        ["Settings_AutoClaimChannelPoints"] = "Réclamer automatiquement les points de chaîne sur la chaîne regardée",
        ["Settings_WhenOverridingHarvest"] = "Lors d'un forçage, récolter",
        ["Settings_WhenOverridingHarvestDescription"] = "Ce que fait un clic sur « Récolter » sur une campagne : toute la campagne, seulement son prochain drop (puis retour à l'automatique), ou demander à chaque fois.",
        ["Settings_PriorityGames"] = "JEUX PRIORITAIRES (HAUT = EN PREMIER)",
        ["Settings_StartTypingGameName"] = "Commencez à taper le nom d'un jeu...",
        ["Settings_Add"] = "Ajouter",
        ["Settings_DragToReorder"] = "Faites glisser par la poignée ≡ pour réorganiser (ou utilisez les flèches). Haut = récolté en premier.",
        ["Settings_ExcludedGames"] = "JEUX EXCLUS",
        ["Settings_ExcludedGamesDescription"] = "Les jeux de cette liste ne sont jamais récoltés - leurs campagnes de drops sont entièrement ignorées, même lorsque le jeu est lié et a des streams en direct. Utilisez-la pour ignorer les jeux dont vous ne voulez pas les drops.",
        ["Settings_DedupeGames"] = "DÉDUPLICATION DES JEUX",
        ["Settings_DedupeGamesDescription"] = "Pour les jeux ajoutés ici, ignorer les drops dont vous possédez déjà la récompense (d'après l'historique de réclamations de Twitch sur ~6 mois).",
        ["Settings_HarvestUnlinkedGames"] = "RÉCOLTER LES JEUX NON LIÉS",
        ["Settings_HarvestUnlinkedGamesDescription"] = "Récolter les campagnes de ces jeux même sans lien de compte. Toujours récoltées EN DERNIER (après toutes les campagnes liées), et peuvent ne pas être créditées si la campagne exige réellement un lien.",
        ["Settings_PreferredChannels"] = "CHAÎNES PRÉFÉRÉES (⭐)",
        ["Settings_PreferredChannelsDescription"] = "Ajoutez une chaîne ci-dessous, ou faites un clic droit sur une chaîne dans l'onglet Chaînes. Lorsqu'une chaîne préférée est en direct pour le jeu en cours de récolte et qu'aucune chaîne de campagne officielle n'est requise, DropHarvester y reste inactif au lieu d'un stream aléatoire à forte audience - le drop est quand même crédité, vous soutenez donc le streamer sans coût pour la récolte. La priorité/expiration la plus proche décide toujours quel jeu est récolté ; une chaîne officielle l'emporte toujours.",
        ["Settings_PreferredChannelPlaceholder"] = "Identifiant de chaîne (ex. ninja)",
        ["Settings_NoChannelsYet"] = "Aucune pour l'instant - ajoutez-en une ci-dessus ou par un clic droit sur une chaîne.",
        ["Settings_AvoidedChannels"] = "CHAÎNES ÉVITÉES (🚫)",
        ["Settings_AvoidedChannelsDescription"] = "Ajoutez une chaîne ci-dessous, ou faites un clic droit sur une chaîne dans l'onglet Chaînes. Une chaîne évitée n'est jamais utilisée en veille sauf si c'est le seul stream avec drops activés en direct pour le jeu en ce moment (dernier recours).",
        ["Settings_AvoidedChannelPlaceholder"] = "Identifiant de chaîne (ex. unstreamer)",
        ["Settings_DropClaimedSound"] = "SON DE DROP RÉCLAMÉ",
        ["Settings_PlaySoundOnDropClaimed"] = "Jouer un son lorsqu'un drop est réclamé",
        ["Settings_Choose"] = "Choisir...",
        ["Settings_Test"] = "Tester",
        ["Settings_ClearSound"] = "Effacer le son",
        ["Settings_Volume"] = "Volume",
        ["Settings_OutputDevice"] = "Périphérique de sortie (Windows peut cibler n'importe quel périphérique ; macOS utilise le périphérique système par défaut)",
        ["Settings_DesktopNotifications"] = "NOTIFICATIONS DE BUREAU",
        ["Settings_DropClaimed"] = "Drop réclamé",
        ["Settings_CampaignComplete"] = "Campagne terminée",
        ["Settings_AllDropsHarvested"] = "Tous les drops récoltés",
        ["Settings_LoginExpired"] = "Session expirée",
        ["Settings_RemoteWebhookAlerts"] = "ALERTES WEBHOOK À DISTANCE",
        ["Settings_EnableWebhookAlerts"] = "Activer les alertes webhook",
        ["Settings_WebhookType"] = "Type de webhook",
        ["Settings_WebhookUrl"] = "URL du webhook",
        ["Settings_SendTestMessage"] = "Envoyer un message de test",
        ["Settings_SendOn"] = "ENVOYER LORS DE",
        ["Settings_NewDropAvailable"] = "Nouveau drop disponible pour le jeu",
        ["Settings_Log"] = "JOURNAL",
        ["Settings_TimestampOnEachLine"] = "Horodatage affiché sur chaque ligne de journal",
        ["Settings_Application"] = "APPLICATION",
        ["Settings_MinimizeToTray"] = "Réduire dans la barre d'état à la fermeture",
        ["Settings_StartWithSystem"] = "Démarrer avec le système",
        ["Settings_StartMinimizedToTray"] = "Démarrer réduit dans la barre d'état",
        ["Settings_StartMinimizedToTrayDescription"] = "Se lancer directement dans la barre d'état plutôt qu'à l'écran - à chaque lancement, que vous l'ouvriez vous-même ou qu'il démarre avec le système.",
        ["Settings_ProxyOptional"] = "Proxy (facultatif)",
        ["Settings_ProxyPlaceholder"] = "http://host:port",
        ["Settings_DebugServer"] = "SERVEUR DE DÉBOGAGE",
        ["Settings_RunLocalDebugServer"] = "Exécuter le serveur de débogage local",
        ["Settings_RunLocalDebugServerDescription"] = "Expose l'état en direct et chaque décision de récolte/ignorer/réclamation au format JSON sur localhost - pour diagnostiquer ce que l'application fait en coulisses.",
        ["Settings_Port"] = "Port",

        // ----- engine status + common log lines -----
        ["Status_Starting"] = "Démarrage...",
        ["Status_Stopped"] = "Arrêté",
        ["Status_NoDropsToHarvest"] = "Aucun drop à récolter",
        ["Status_WaitingForStream"] = "Drops disponibles - en attente qu'un stream se mette en ligne",
        ["Status_WatchingChannelGame"] = "Visionnage de {0} - {1}",
        ["Status_ChannelWentOffline"] = "{0} est passé hors ligne",
        ["Log_HarvestingStarted"] = "Récolte démarrée.",
        ["Log_HarvestingStopped"] = "Récolte arrêtée.",
        ["Log_ConnectionReestablished"] = "Connexion rétablie - reprise de la récolte.",
        ["Log_ConnectionLost"] = "Les Twitch Drops semblent indisponibles ou la connexion a été perdue - récolte en pause ; elle reprendra automatiquement dès le rétablissement.",

        // ----- Status/login view-model strings -----
        ["Status_Idle"] = "Inactif",
        ["Status_NotLoggedIn"] = "Non connecté",
        ["Status_LoggedInAs"] = "Connecté en tant que {0} (id {1})",
        ["Status_ConnectionIssue"] = "Les Twitch Drops rencontrent des problèmes ou vous avez perdu la connexion. Nous reprendrons automatiquement la récolte dès que la connexion aura été rétablie.",
        ["Status_DropsOutage"] = "Twitch accepte les visionnages mais ne crédite pas la progression des drops pour le moment (une panne côté Twitch). La récolte continue et reprendra automatiquement une fois le problème résolu.",
        ["Login_Requesting"] = "Demande d'un code de connexion à Twitch...",
        ["Login_GoToAndEnter"] = "Rendez-vous sur {0} et saisissez le code {1}",
        ["Login_NotCompleted"] = "La connexion n'a pas été terminée. Veuillez réessayer.",
        ["Login_Cancelled"] = "Connexion annulée.",
        ["Login_Failed"] = "Échec de la connexion : {0}",
        ["Login_Expired"] = "Votre session Twitch a expiré - veuillez vous reconnecter.",
        ["Override_HarvestPrompt"] = "Forçage - récolter :",
        ["Override_JustNextDrop"] = "Seulement le prochain drop",
        ["Override_EntireCampaign"] = "Toute la campagne",
        ["Override_AskEachTime"] = "Me demander à chaque fois",

        // ----- Inventory load status -----
        ["Inventory_LoadingDrops"] = "Chargement des drops... {0}/{1}",
        ["Inventory_Loaded"] = "{0} campagnes.",
        ["Inventory_None"] = "Aucune campagne trouvée.",
        ["Inventory_LoadFailed"] = "Échec du chargement : {0}",

        // ----- Channels view-model -----
        ["Channels_CountText"] = "{0} chaînes en direct sur {1} jeux",
        ["Channels_UnknownGame"] = "Inconnu",
        ["Channels_OneLive"] = "1 en direct",
        ["Channels_NLive"] = "{0} en direct",

        // ----- Campaigns view-model -----
        ["Campaigns_ListView"] = "Vue en liste",
        ["Campaigns_GridView"] = "Vue en grille",
        ["Inventory_LogInFirst"] = "Connectez-vous d'abord pour voir votre inventaire.",
        ["Inventory_LoadingCampaigns"] = "Chargement des campagnes...",

        // ----- Stats view-model -----
        ["Stats_ExportedJson"] = "JSON exporté vers {0}",
        ["Stats_ExportedCsv"] = "CSV exporté vers {0}",
        ["Stats_Since"] = "Depuis {0}",

        // ----- Log view-model -----
        ["Log_Copy"] = "Copier",
        ["Log_Copied"] = "Copié !",
        ["Log_CopyFailed"] = "Échec de la copie",

        // ----- Settings view-model -----
        ["Settings_NoSoundChosen"] = "Aucun son choisi",
        ["Settings_ChooseSoundTitle"] = "Choisir un son à jouer lorsqu'un drop est réclamé",
        ["Settings_SoundPickFailed"] = "Impossible de choisir un fichier : {0}",
        ["Settings_AudioNotAvailable"] = "La lecture audio n'est pas disponible sur cette plateforme.",
        ["Settings_ChooseSoundFirst"] = "Choisissez d'abord un fichier son.",
        ["Settings_SystemDefault"] = "Par défaut du système",
        ["Settings_PlayingOn"] = "Lecture sur {0} à {1}...",
        ["Settings_InvalidGameHint"] = "Ce n'est pas un jeu Twitch valide - choisissez une suggestion.",
        ["Settings_TimestampDate"] = "Date",
        ["Settings_TimestampTime"] = "Heure",
        ["Settings_TimestampDateAndTime"] = "Date et heure",
        ["Settings_TimestampTimeAndDate"] = "Heure et date",
        ["Settings_Clock12Hour"] = "Format 12 heures",
        ["Settings_Clock24Hour"] = "Format 24 heures",
        ["Settings_CurrentVersion"] = "Vous utilisez la v{0}.",
        ["Settings_UpdateReadyStatus"] = "La mise à jour v{0} est prête - cliquez sur Mettre à jour maintenant pour l'installer.",
        ["Settings_CheckingForUpdates"] = "Recherche de mises à jour...",
        ["Settings_UpdateServerUnreachable"] = "Impossible de joindre le serveur de mise à jour.",
        ["Settings_OnLatestVersion"] = "Vous utilisez la dernière version (v{0}).",
        ["Settings_DownloadingUpdate"] = "Téléchargement de la mise à jour v{0}...",
        ["Settings_UpdateReadyAutoInstall"] = "La mise à jour v{0} est prête - cliquez sur Mettre à jour maintenant pour l'installer, ou elle s'installe automatiquement au prochain redémarrage.",
        ["Settings_UpdateDownloadFailed"] = "Échec du téléchargement de la mise à jour - réessayez.",
        ["Settings_UpdateCheckFailed"] = "Échec de la recherche de mise à jour.",
        ["Settings_InstallingUpdate"] = "Installation de la mise à jour - l'application va redémarrer...",
        ["Settings_InstallerStartFailed"] = "Impossible de démarrer l'installateur - il s'installera automatiquement au prochain redémarrage.",
        ["Settings_DebugServerRunning"] = "En cours d'exécution - ouvrez {0} (localhost uniquement)",
        ["Settings_DebugServerOff"] = "Désactivé",
        ["Settings_Hide"] = "Masquer",
        ["Settings_Show"] = "Afficher",
        ["Settings_WebhookGeneric"] = "Générique",
        ["Settings_Sending"] = "Envoi...",
        ["Settings_WebhookEnterUrlFirst"] = "Saisissez d'abord une URL de webhook.",
        ["Settings_WebhookTestSent"] = "Message de test envoyé.",
        ["Settings_WebhookReturnedError"] = "Le webhook a renvoyé une erreur.",
        ["Settings_WebhookFailed"] = "Échec : {0}",

        // ----- Twitch model display -----
        ["Model_RemovePreferred"] = "⭐ Retirer des préférées",
        ["Model_PreferChannel"] = "⭐ Préférer cette chaîne",
        ["Model_RemoveAvoided"] = "\U0001F6AB Retirer des évitées",
        ["Model_AvoidChannel"] = "\U0001F6AB Éviter cette chaîne",
        ["Model_ChannelLive"] = "EN DIRECT - {0}",
        ["Model_ChannelOffline"] = "hors ligne",
        ["Model_DropProgress"] = "{0}/{1} min",
        ["Model_DropProgressSummary"] = "{0}  ({1}/{2} min)",
        ["Model_Remaining"] = "{0} restant",
        ["Model_Linked"] = "Lié",
        ["Model_LinkNeeded"] = "Lien requis",
        ["Model_Ends"] = "Se termine {0}",
    };
}
