namespace DropHarvester.Localization;

/// <summary>Deutsch (German) string table. Any key not present falls back to the English base.</summary>
public static partial class LocStrings
{
    public static readonly Dictionary<string, string> De = new(StringComparer.Ordinal)
    {
        // ----- common -----
        ["Common_Cancel"] = "Abbrechen",
        ["Common_Harvest"] = "Ernten",
        ["Common_Harvesting"] = "Ernte läuft",

        // ----- tab titles -----
        ["Tab_Status"] = "Status",
        ["Tab_Inventory"] = "Inventar",
        ["Tab_Channels"] = "Kanäle",
        ["Tab_Settings"] = "Einstellungen",
        ["Tab_Log"] = "Protokoll",
        ["Tab_Stats"] = "Statistik",

        // ----- Status page -----
        ["Status_UpdateReady"] = "Update bereit",
        ["Status_UpdateNow"] = "Jetzt aktualisieren",
        ["Status_UpdateAvailableTitle"] = "Update verfügbar",
        ["Status_UpdateAvailableDetail"] = "Version v{0} ist verfügbar - ein Update wird dringend empfohlen.",
        ["Status_UpdateDownloading"] = "v{0} wird heruntergeladen...",
        ["Status_Download"] = "Herunterladen",
        ["Status_Account"] = "KONTO",
        ["Status_LogIn"] = "Mit Twitch anmelden",
        ["Status_LogOut"] = "Abmelden",
        ["Status_AuthorizeHeader"] = "DIESE APP AUTORISIEREN",
        ["Status_AuthorizeBody"] = "Es wurde ein Browserfenster geöffnet. Gib diesen Code ein, um dein Twitch-Konto zu verknüpfen:",
        ["Status_Harvesting"] = "ERNTE",
        ["Status_StartHarvesting"] = "Ernte starten",
        ["Status_PauseHarvesting"] = "Ernte pausieren",
        ["Status_Channel"] = "Kanal",
        ["Status_Game"] = "Spiel",
        ["Status_Campaign"] = "Kampagne",
        ["Status_CampaignProgress"] = "Kampagnenfortschritt",
        ["Status_UpNext"] = "ALS NÄCHSTES",
        ["Status_Queue"] = "WARTESCHLANGE",
        ["Status_RemoveOverride"] = "Manuelle Auswahl entfernen",
        ["Status_AllowNewHigherPriority"] = "Neuen Kampagnen mit höherer Priorität erlauben, diese manuelle Auswahl zu beenden",

        // ----- Settings: language -----
        ["Settings_Language"] = "Sprache",
        ["Settings_LanguageNav"] = "Sprache",

        // ----- notifications -----
        ["Notif_NameDashGame"] = "{0} - {1}",
        ["Notif_DropClaimed"] = "Drop eingesammelt",
        ["Notif_CampaignComplete"] = "Kampagne abgeschlossen",
        ["Notif_AllHarvested"] = "Alle Drops geerntet",
        ["Notif_AllHarvestedBody"] = "Derzeit sind keine weiteren Drops zum Ernten verfügbar.",
        ["Notif_NewDrop"] = "Neuer Drop verfügbar",
        ["Notif_LoginExpired"] = "Anmeldung abgelaufen",
        ["Notif_LoginExpiredBody"] = "Deine Twitch-Sitzung ist abgelaufen - bitte melde dich erneut an.",

        // ----- Campaigns / Inventory page -----
        ["Campaigns_Refresh"] = "Aktualisieren",
        ["Campaigns_Upcoming"] = "Bevorstehend",
        ["Campaigns_Expired"] = "Abgelaufen",
        ["Campaigns_NotLinked"] = "Nicht verknüpft",
        ["Campaigns_Finished"] = "Abgeschlossen",
        ["Campaigns_Excluded"] = "Ausgeschlossen",
        ["Campaigns_Deduped"] = "Entduppliziert",
        ["Campaigns_NoMatch"] = "Keine Kampagnen entsprechen den aktuellen Filtern.",
        ["Campaigns_Harvesting"] = "Ernte läuft",
        ["Campaigns_Claimed"] = "Eingesammelt",
        ["Campaigns_ClaimedBadge"] = "Eingesammelt",

        // ----- Channels page -----
        ["Channels_Updating"] = "Wird aktualisiert...",
        ["Channels_EmptyView"] = "Noch keine Kanäle erfasst. Die Ernte füllt diese Liste, sobald eine Kampagne aktiv ist.",
        ["Channels_Channel"] = "KANAL",
        ["Channels_Official"] = "OFFIZIELL",
        ["Channels_Viewers"] = "ZUSCHAUER",
        ["Channels_Status"] = "STATUS",
        ["Channels_Watch"] = "Ansehen",
        ["Channels_Switching"] = "Wird gewechselt...",
        ["Channels_Harvesting"] = "Ernte läuft",

        // ----- Stats page -----
        ["Stats_DropsClaimed"] = "Drops eingesammelt",
        ["Stats_CampaignsDone"] = "Kampagnen erledigt",
        ["Stats_WatchTimeSaved"] = "Zeit mit Ernten",
        ["Stats_DropsClaimedLast7Days"] = "EINGESAMMELTE DROPS (LETZTE 7 TAGE)",
        ["Stats_ExportCsv"] = "CSV exportieren",
        ["Stats_ExportJson"] = "JSON exportieren",
        ["Stats_RecentHistory"] = "LETZTER VERLAUF",
        ["Stats_NoHistoryYet"] = "Noch kein Verlauf.",

        // ----- Log page -----
        ["Log_Clear"] = "Leeren",
        ["Log_NoLogOutputYet"] = "Noch keine Protokollausgabe.",

        // ----- Settings page -----
        ["Settings_Settings"] = "EINSTELLUNGEN",
        ["Settings_NavUpdates"] = "Updates",
        ["Settings_NavHarvesting"] = "Ernte",
        ["Settings_NavPriorityGames"] = "Prioritätsspiele",
        ["Settings_NavExcludedGames"] = "Ausgeschlossene Spiele",
        ["Settings_NavDedupeGames"] = "Entduplizierungs-Spiele",
        ["Settings_NavUnlinkedGames"] = "Nicht verknüpfte Spiele",
        ["Settings_NavPreferredChannels"] = "Bevorzugte Kanäle",
        ["Settings_NavAvoidedChannels"] = "Gemiedene Kanäle",
        ["Settings_NavDropSound"] = "Drop-Ton",
        ["Settings_NavNotifications"] = "Benachrichtigungen",
        ["Settings_NavWebhookAlerts"] = "Webhook-Benachrichtigungen",
        ["Settings_NavLog"] = "Protokoll",
        ["Settings_NavApplication"] = "Anwendung",
        ["Settings_NavDebugServer"] = "Debug-Server",
        ["Settings_Updates"] = "UPDATES",
        ["Settings_AutoCheckUpdates"] = "Beim Start automatisch nach Updates suchen",
        ["Settings_UpdatesDescription"] = "Sucht beim Start und einmal täglich auf GitHub nach einer neuen Version. Wenn eine verfügbar ist, kannst du sie über ein Banner im Status-Tab herunterladen und hier oder dort installieren - oder sie installiert sich beim nächsten Neustart.",
        ["Settings_CheckNow"] = "Jetzt suchen",
        ["Settings_UpdateNow"] = "Jetzt aktualisieren",
        ["Settings_Harvesting"] = "ERNTE",
        ["Settings_HarvestOnlyPriority"] = "Nur Prioritätsspiele ernten",
        ["Settings_PrioritizeEndingSoonest"] = "Am schnellsten endende priorisieren",
        ["Settings_PrioritizeEndingSoonestDescription"] = "Ernte diejenige geeignete Kampagne, die zuerst abläuft - beachte aber weiterhin die Prioritätsliste, wenn Zeit bleibt: Ein Prioritäts-Drop wird vor einem früher endenden geerntet, sofern das Aufschieben ihn nicht verlieren würde, und ein früher endender Nicht-Prioritäts-Drop wird nur gewählt, wenn er dich keinen Prioritäts-Drop kostet.",
        ["Settings_PrioritizeByAvailability"] = "Nach Verfügbarkeit priorisieren",
        ["Settings_PrioritizeByAvailabilityDescription"] = "Nur als Gleichstandsentscheidung: Wenn Kampagnen in der obigen Reihenfolge ansonsten gleichauf sind, ernte zuerst diejenige, deren Spiel weniger live Drops-fähige Streamer hat - so schnappst du dir Drops aus knappen Streams, solange ein Kanal live ist, und lässt reichlich verfügbare Spiele warten. Überschreibt niemals deine Prioritätsliste.",
        ["Settings_HarvestImpossibleDrops"] = "Unmögliche Drops ernten",
        ["Settings_HarvestImpossibleDropsDescription"] = "Sieh dir Drops an, die vor dem Ende der Kampagne nicht fertig werden können (falls sie verlängert wird).",
        ["Settings_ShowUnlinkedInChannels"] = "Nicht verknüpfte Spiele in Kanäle anzeigen",
        ["Settings_ShowUnlinkedInChannelsDescription"] = "Standardmäßig aus. Das Überspringen der Kanäle nicht verknüpfter Spiele spart Verzeichnisabfragen (API-Aufrufe).",
        ["Settings_IncludeBadgeEmote"] = "Abzeichen-/Emote-Kampagnen einbeziehen (ohne Verknüpfung)",
        ["Settings_AutoClaimChannelPoints"] = "Kanalpunkte auf dem angesehenen Kanal automatisch einsammeln",
        ["Settings_WhenOverridingHarvest"] = "Bei manueller Auswahl ernten",
        ["Settings_WhenOverridingHarvestDescription"] = "Was ein Klick auf \"Ernten\" bei einer Kampagne bewirkt: die gesamte Kampagne, nur ihren nächsten Drop (dann zurück zur Automatik) oder jedes Mal nachfragen.",
        ["Settings_PriorityGames"] = "PRIORITÄTSSPIELE (OBEN = ZUERST)",
        ["Settings_StartTypingGameName"] = "Beginne, einen Spielnamen einzugeben...",
        ["Settings_Add"] = "Hinzufügen",
        ["Settings_DragToReorder"] = "Zum Umordnen am ≡-Griff ziehen (oder die Pfeile verwenden). Oben = zuerst geerntet.",
        ["Settings_ExcludedGames"] = "AUSGESCHLOSSENE SPIELE",
        ["Settings_ExcludedGamesDescription"] = "Spiele auf dieser Liste werden nie geerntet - ihre Drop-Kampagnen werden vollständig übersprungen, selbst wenn das Spiel verknüpft ist und Live-Streams hat. Verwende sie, um Spiele zu ignorieren, für die du keine Drops möchtest.",
        ["Settings_DedupeGames"] = "ENTDUPLIZIERUNGS-SPIELE",
        ["Settings_DedupeGamesDescription"] = "Bei hier hinzugefügten Spielen werden Drops übersprungen, deren Belohnung du bereits besitzt (aus Twitchs Einsammel-Verlauf von etwa 6 Monaten).",
        ["Settings_HarvestUnlinkedGames"] = "NICHT VERKNÜPFTE SPIELE ERNTEN",
        ["Settings_HarvestUnlinkedGamesDescription"] = "Ernte die Kampagnen dieser Spiele auch ohne Kontoverknüpfung. Sie werden immer ZULETZT geerntet (nach jeder verknüpften Kampagne) und werden möglicherweise nicht gutgeschrieben, wenn die Kampagne tatsächlich eine Verknüpfung erfordert.",
        ["Settings_PreferredChannels"] = "BEVORZUGTE KANÄLE (⭐)",
        ["Settings_PreferredChannelsDescription"] = "Füge unten einen Kanal hinzu oder klicke mit der rechten Maustaste auf einen im Kanäle-Tab. Wenn ein bevorzugter Kanal für das gerade geerntete Spiel live ist und kein offizieller Kampagnenkanal erforderlich ist, verweilt DropHarvester auf diesem statt auf einem zufälligen Stream mit vielen Zuschauern - der Drop wird trotzdem gutgeschrieben, sodass du den Streamer ohne Nachteil für die Ernte unterstützt. Priorität/am schnellsten endend entscheidet weiterhin, welches Spiel geerntet wird; ein offizieller Kanal gewinnt immer.",
        ["Settings_PreferredChannelPlaceholder"] = "Kanal-Login (z. B. ninja)",
        ["Settings_NoChannelsYet"] = "Noch keine - füge oben einen hinzu oder klicke mit der rechten Maustaste auf einen Kanal.",
        ["Settings_AvoidedChannels"] = "GEMIEDENE KANÄLE (🚫)",
        ["Settings_AvoidedChannelsDescription"] = "Füge unten einen Kanal hinzu oder klicke mit der rechten Maustaste auf einen im Kanäle-Tab. Auf einem gemiedenen Kanal wird nie verweilt, es sei denn, es ist gerade der einzige live Drops-fähige Stream für das Spiel (letzter Ausweg).",
        ["Settings_AvoidedChannelPlaceholder"] = "Kanal-Login (z. B. somestreamer)",
        ["Settings_DropClaimedSound"] = "TON BEI EINGESAMMELTEM DROP",
        ["Settings_PlaySoundOnDropClaimed"] = "Einen Ton abspielen, wenn ein Drop eingesammelt wird",
        ["Settings_Choose"] = "Auswählen...",
        ["Settings_Test"] = "Testen",
        ["Settings_ClearSound"] = "Ton entfernen",
        ["Settings_Volume"] = "Lautstärke",
        ["Settings_OutputDevice"] = "Ausgabegerät (Windows kann jedes Gerät ansteuern; macOS verwendet den Systemstandard)",
        ["Settings_DesktopNotifications"] = "DESKTOP-BENACHRICHTIGUNGEN",
        ["Settings_DropClaimed"] = "Drop eingesammelt",
        ["Settings_CampaignComplete"] = "Kampagne abgeschlossen",
        ["Settings_AllDropsHarvested"] = "Alle Drops geerntet",
        ["Settings_LoginExpired"] = "Anmeldung abgelaufen",
        ["Settings_RemoteWebhookAlerts"] = "REMOTE-WEBHOOK-BENACHRICHTIGUNGEN",
        ["Settings_EnableWebhookAlerts"] = "Webhook-Benachrichtigungen aktivieren",
        ["Settings_WebhookType"] = "Webhook-Typ",
        ["Settings_WebhookUrl"] = "Webhook-URL",
        ["Settings_SendTestMessage"] = "Testnachricht senden",
        ["Settings_SendOn"] = "SENDEN BEI",
        ["Settings_NewDropAvailable"] = "Neuer Drop für Spiel verfügbar",
        ["Settings_Log"] = "PROTOKOLL",
        ["Settings_TimestampOnEachLine"] = "Zeitstempel in jeder Protokollzeile anzeigen",
        ["Settings_Application"] = "ANWENDUNG",
        ["Settings_MinimizeToTray"] = "Beim Schließen in die Taskleiste minimieren",
        ["Settings_StartWithSystem"] = "Mit dem System starten",
        ["Settings_StartMinimizedToTray"] = "Minimiert in der Taskleiste starten",
        ["Settings_StartMinimizedToTrayDescription"] = "Direkt in die Taskleiste starten statt auf dem Bildschirm - bei jedem Start, egal ob du sie selbst öffnest oder sie mit dem System startet.",
        ["Settings_ProxyOptional"] = "Proxy (optional)",
        ["Settings_ProxyPlaceholder"] = "http://host:port",
        ["Settings_DebugServer"] = "DEBUG-SERVER",
        ["Settings_RunLocalDebugServer"] = "Lokalen Debug-Server ausführen",
        ["Settings_RunLocalDebugServerDescription"] = "Stellt den Live-Zustand und jede Ernte-/Überspring-/Einsammel-Entscheidung als JSON auf localhost bereit - zum Diagnostizieren, was die App im Hintergrund tut.",
        ["Settings_Port"] = "Port",

        // ----- engine status + common log lines -----
        ["Status_Starting"] = "Wird gestartet...",
        ["Status_Stopped"] = "Gestoppt",
        ["Status_NoDropsToHarvest"] = "Keine Drops zum Ernten",
        ["Status_WaitingForStream"] = "Drops verfügbar - warte darauf, dass ein Stream online geht",
        ["Status_WatchingChannelGame"] = "Sieht {0} - {1}",
        ["Status_ChannelWentOffline"] = "{0} ist offline gegangen",
        ["Log_HarvestingStarted"] = "Ernte gestartet.",
        ["Log_HarvestingStopped"] = "Ernte gestoppt.",
        ["Log_ConnectionReestablished"] = "Verbindung wiederhergestellt - Ernte wird fortgesetzt.",
        ["Log_ConnectionLost"] = "Twitch Drops scheinen ausgefallen zu sein oder die Verbindung wurde unterbrochen - Ernte pausiert; sie wird automatisch fortgesetzt, sobald sie wieder da ist.",

        // ----- Status/login view-model strings -----
        ["Status_Idle"] = "Untätig",
        ["Status_NotLoggedIn"] = "Nicht angemeldet",
        ["Status_LoggedInAs"] = "Angemeldet als {0} (ID {1})",
        ["Status_ConnectionIssue"] = "Twitch Drops haben Probleme oder du hast die Verbindung verloren. Wir setzen die Ernte automatisch fort, sobald die Verbindung wiederhergestellt ist.",
        ["Login_Requesting"] = "Fordere einen Anmeldecode von Twitch an...",
        ["Login_GoToAndEnter"] = "Gehe zu {0} und gib den Code {1} ein",
        ["Login_NotCompleted"] = "Die Anmeldung wurde nicht abgeschlossen. Bitte versuche es erneut.",
        ["Login_Cancelled"] = "Anmeldung abgebrochen.",
        ["Login_Failed"] = "Anmeldung fehlgeschlagen: {0}",
        ["Login_Expired"] = "Deine Twitch-Sitzung ist abgelaufen - bitte melde dich erneut an.",
        ["Override_HarvestPrompt"] = "Manuelle Auswahl - ernten:",
        ["Override_JustNextDrop"] = "Nur den nächsten Drop",
        ["Override_EntireCampaign"] = "Gesamte Kampagne",
        ["Override_AskEachTime"] = "Jedes Mal nachfragen",

        // ----- Inventory load status -----
        ["Inventory_LoadingDrops"] = "Lade Drops... {0}/{1}",
        ["Inventory_Loaded"] = "{0} Kampagnen.",
        ["Inventory_None"] = "Keine Kampagnen gefunden.",
        ["Inventory_LoadFailed"] = "Laden fehlgeschlagen: {0}",

        // ----- Channels view-model -----
        ["Channels_CountText"] = "{0} Live-Kanäle über {1} Spiele",
        ["Channels_UnknownGame"] = "Unbekannt",
        ["Channels_OneLive"] = "1 live",
        ["Channels_NLive"] = "{0} live",

        // ----- Campaigns view-model -----
        ["Campaigns_ListView"] = "Listenansicht",
        ["Campaigns_GridView"] = "Rasteransicht",
        ["Inventory_LogInFirst"] = "Melde dich zuerst an, um dein Inventar zu sehen.",
        ["Inventory_LoadingCampaigns"] = "Lade Kampagnen...",

        // ----- Stats view-model -----
        ["Stats_ExportedJson"] = "JSON nach {0} exportiert",
        ["Stats_ExportedCsv"] = "CSV nach {0} exportiert",
        ["Stats_Since"] = "Seit {0}",

        // ----- Log view-model -----
        ["Log_Copy"] = "Kopieren",
        ["Log_Copied"] = "Kopiert!",
        ["Log_CopyFailed"] = "Kopieren fehlgeschlagen",

        // ----- Settings view-model -----
        ["Settings_NoSoundChosen"] = "Kein Ton ausgewählt",
        ["Settings_ChooseSoundTitle"] = "Wähle einen Ton, der abgespielt wird, wenn ein Drop eingesammelt wird",
        ["Settings_SoundPickFailed"] = "Datei konnte nicht ausgewählt werden: {0}",
        ["Settings_AudioNotAvailable"] = "Die Audiowiedergabe ist auf dieser Plattform nicht verfügbar.",
        ["Settings_ChooseSoundFirst"] = "Wähle zuerst eine Tondatei.",
        ["Settings_SystemDefault"] = "Systemstandard",
        ["Settings_PlayingOn"] = "Wiedergabe auf {0} mit {1}...",
        ["Settings_InvalidGameHint"] = "Kein gültiges Twitch-Spiel - wähle einen Vorschlag.",
        ["Settings_TimestampDate"] = "Datum",
        ["Settings_TimestampTime"] = "Uhrzeit",
        ["Settings_TimestampDateAndTime"] = "Datum und Uhrzeit",
        ["Settings_TimestampTimeAndDate"] = "Uhrzeit und Datum",
        ["Settings_Clock12Hour"] = "12-Stunden-Format",
        ["Settings_Clock24Hour"] = "24-Stunden-Format",
        ["Settings_CurrentVersion"] = "Du hast v{0}.",
        ["Settings_UpdateReadyStatus"] = "Update v{0} ist bereit - klicke auf Jetzt aktualisieren, um es zu installieren.",
        ["Settings_CheckingForUpdates"] = "Suche nach Updates...",
        ["Settings_UpdateServerUnreachable"] = "Der Update-Server war nicht erreichbar.",
        ["Settings_OnLatestVersion"] = "Du hast die neueste Version (v{0}).",
        ["Settings_DownloadingUpdate"] = "Lade Update v{0} herunter...",
        ["Settings_UpdateReadyAutoInstall"] = "Update v{0} ist bereit - klicke auf Jetzt aktualisieren, um es zu installieren, oder es wird beim nächsten Neustart automatisch installiert.",
        ["Settings_UpdateDownloadFailed"] = "Update-Download fehlgeschlagen - versuche es erneut.",
        ["Settings_UpdateCheckFailed"] = "Update-Suche fehlgeschlagen.",
        ["Settings_InstallingUpdate"] = "Update wird installiert - die App startet neu...",
        ["Settings_InstallerStartFailed"] = "Der Installer konnte nicht gestartet werden - er wird beim nächsten Neustart automatisch installiert.",
        ["Settings_DebugServerRunning"] = "Läuft - öffne {0} (nur localhost)",
        ["Settings_DebugServerOff"] = "Aus",
        ["Settings_Hide"] = "Ausblenden",
        ["Settings_Show"] = "Anzeigen",
        ["Settings_WebhookGeneric"] = "Generisch",
        ["Settings_Sending"] = "Wird gesendet...",
        ["Settings_WebhookEnterUrlFirst"] = "Gib zuerst eine Webhook-URL ein.",
        ["Settings_WebhookTestSent"] = "Testnachricht gesendet.",
        ["Settings_WebhookReturnedError"] = "Der Webhook hat einen Fehler zurückgegeben.",
        ["Settings_WebhookFailed"] = "Fehlgeschlagen: {0}",

        // ----- Twitch model display -----
        ["Model_RemovePreferred"] = "⭐ Bevorzugung entfernen",
        ["Model_PreferChannel"] = "⭐ Diesen Kanal bevorzugen",
        ["Model_RemoveAvoided"] = "\U0001F6AB Meidung entfernen",
        ["Model_AvoidChannel"] = "\U0001F6AB Diesen Kanal meiden",
        ["Model_ChannelLive"] = "LIVE - {0}",
        ["Model_ChannelOffline"] = "offline",
        ["Model_DropProgress"] = "{0}/{1} Min.",
        ["Model_DropProgressSummary"] = "{0}  ({1}/{2} Min.)",
        ["Model_Remaining"] = "{0} verbleibend",
        ["Model_Linked"] = "Verknüpft",
        ["Model_LinkNeeded"] = "Verknüpfung nötig",
        ["Model_Ends"] = "Endet {0}",
    };
}
