namespace DropHarvester.Localization;

/// <summary>简体中文 (Simplified Chinese) string table. Any key not present falls back to the English base.</summary>
public static partial class LocStrings
{
    public static readonly Dictionary<string, string> ZhHans = new(StringComparer.Ordinal)
    {
        // ----- common -----
        ["Common_Cancel"] = "取消",
        ["Common_Harvest"] = "收取",
        ["Common_Harvesting"] = "收取中",

        // ----- tab titles -----
        ["Tab_Status"] = "状态",
        ["Tab_Inventory"] = "库存",
        ["Tab_Channels"] = "频道",
        ["Tab_Settings"] = "设置",
        ["Tab_Log"] = "日志",
        ["Tab_Stats"] = "统计",

        // ----- Status page -----
        ["Status_UpdateReady"] = "更新已就绪",
        ["Status_UpdateNow"] = "立即更新",
        ["Status_UpdateAvailableTitle"] = "有可用更新",
        ["Status_UpdateAvailableDetail"] = "版本 v{0} 可用 - 强烈建议更新。",
        ["Status_UpdateDownloading"] = "正在下载 v{0}...",
        ["Status_Download"] = "下载",
        ["Status_Account"] = "账户",
        ["Status_LogIn"] = "使用 Twitch 登录",
        ["Status_LogOut"] = "退出登录",
        ["Status_AuthorizeHeader"] = "授权此应用",
        ["Status_AuthorizeBody"] = "已打开一个浏览器窗口。输入此代码以关联你的 Twitch 账户：",
        ["Status_Harvesting"] = "收取中",
        ["Status_StartHarvesting"] = "开始收取",
        ["Status_PauseHarvesting"] = "暂停收取",
        ["Status_Channel"] = "频道",
        ["Status_Game"] = "游戏",
        ["Status_Campaign"] = "活动",
        ["Status_WatchLive"] = "观看直播",
        ["Status_CampaignProgress"] = "活动进度",
        ["Status_UpNext"] = "接下来",
        ["Status_Queue"] = "队列",
        ["Status_RemoveOverride"] = "移除覆盖",
        ["Status_Overriding"] = "覆盖中...",
        ["Status_AllowNewHigherPriority"] = "允许新的更高优先级活动结束此覆盖",

        // ----- Settings: language -----
        ["Settings_Language"] = "语言",
        ["Settings_LanguageNav"] = "语言",

        // ----- notifications -----
        ["Notif_NameDashGame"] = "{0} - {1}",
        ["Notif_DropClaimed"] = "Drop 已领取",
        ["Notif_CampaignComplete"] = "活动完成",
        ["Notif_AllHarvested"] = "所有 Drops 已收取",
        ["Notif_AllHarvestedBody"] = "目前没有更多可收取的 Drops。",
        ["Notif_NewDrop"] = "有新的 Drop 可领取",
        ["Notif_LoginExpired"] = "登录已过期",
        ["Notif_LoginExpiredBody"] = "你的 Twitch 会话已过期 - 请重新登录。",

        // ----- Campaigns / Inventory page -----
        ["Campaigns_Refresh"] = "刷新",
        ["Campaigns_Upcoming"] = "即将开始",
        ["Campaigns_Expired"] = "已过期",
        ["Campaigns_NotLinked"] = "未关联",
        ["Campaigns_Finished"] = "已完成",
        ["Campaigns_Excluded"] = "已排除",
        ["Campaigns_Deduped"] = "已去重",
        ["Campaigns_SubOnly"] = "仅订阅",
        ["Campaigns_NoMatch"] = "没有符合当前筛选条件的活动。",
        ["Campaigns_Harvesting"] = "收取中",
        ["Campaigns_Claimed"] = "已领取",
        ["Campaigns_ClaimedBadge"] = "已领取",

        // ----- Channels page -----
        ["Channels_Updating"] = "更新中...",
        ["Channels_EmptyView"] = "尚未追踪任何频道。收取会在活动激活后填充此处。",
        ["Channels_Channel"] = "频道",
        ["Channels_Official"] = "官方",
        ["Channels_Viewers"] = "观众",
        ["Channels_Status"] = "状态",
        ["Channels_Watch"] = "观看",
        ["Channels_Switching"] = "切换中...",
        ["Channels_Harvesting"] = "收取中",

        // ----- Stats page -----
        ["Stats_DropsClaimed"] = "已领取 Drops",
        ["Stats_CampaignsDone"] = "已完成活动",
        ["Stats_WatchTimeSaved"] = "收获时长",
        ["Stats_DropsClaimedLast7Days"] = "已领取 DROPS（最近 7 天）",
        ["Stats_ExportCsv"] = "导出 CSV",
        ["Stats_ExportJson"] = "导出 JSON",
        ["Stats_RecentHistory"] = "近期历史",
        ["Stats_NoHistoryYet"] = "暂无历史记录。",

        // ----- Log page -----
        ["Log_Clear"] = "清除",
        ["Log_NoLogOutputYet"] = "暂无日志输出。",

        // ----- Settings page -----
        ["Settings_Settings"] = "设置",
        ["Settings_NavUpdates"] = "更新",
        ["Settings_NavHarvesting"] = "收取",
        ["Settings_NavPriorityGames"] = "优先游戏",
        ["Settings_NavExcludedGames"] = "排除游戏",
        ["Settings_NavDedupeGames"] = "去重游戏",
        ["Settings_NavUnlinkedGames"] = "未关联游戏",
        ["Settings_NavPreferredChannels"] = "偏好频道",
        ["Settings_NavAvoidedChannels"] = "回避频道",
        ["Settings_NavDropSound"] = "Drop 声音",
        ["Settings_NavNotifications"] = "通知",
        ["Settings_NavWebhookAlerts"] = "Webhook 提醒",
        ["Settings_NavLog"] = "日志",
        ["Settings_NavApplication"] = "应用程序",
        ["Settings_NavDebugServer"] = "调试服务器",
        ["Settings_Updates"] = "更新",
        ["Settings_AutoCheckUpdates"] = "启动时自动检查更新",
        ["Settings_UpdatesDescription"] = "在启动时和每天检查 GitHub 上的新版本。有可用版本时，状态选项卡上的横幅可让你下载，然后在此处或那里安装 - 或在下次重启时自动安装。",
        ["Settings_CheckNow"] = "立即检查",
        ["Settings_UpdateNow"] = "立即更新",
        ["Settings_Harvesting"] = "收取",
        ["Settings_HarvestOnlyPriority"] = "仅收取优先游戏",
        ["Settings_PrioritizeEndingSoonest"] = "优先处理最快结束的",
        ["Settings_PrioritizeEndingSoonestDescription"] = "收取最先过期的符合条件的活动 - 但在时间允许时仍会尊重优先列表：只要延后不会导致丢失，优先 Drop 会在较快结束的之前收取；只有在不会让你损失优先 Drop 的情况下，才会选择较快结束的非优先 Drop。",
        ["Settings_PrioritizeByAvailability"] = "按可用性优先",
        ["Settings_PrioritizeByAvailabilityDescription"] = "仅用于打破平局：当活动在上述顺序中打平时，优先收取其游戏拥有较少启用 Drops 直播主的那个 - 趁频道在线时抓取稀缺直播的 Drops，让直播充足的游戏等待。绝不会覆盖你的优先列表。",
        ["Settings_HarvestImpossibleDrops"] = "收取无法完成的 Drops",
        ["Settings_HarvestImpossibleDropsDescription"] = "观看那些在活动结束前无法完成的 Drops（以防活动被延长）。",
        ["Settings_ShowUnlinkedInChannels"] = "在频道中显示未关联的游戏",
        ["Settings_ShowUnlinkedInChannelsDescription"] = "默认关闭。跳过未关联游戏的频道可节省目录查询（API 调用）。",
        ["Settings_IncludeBadgeEmote"] = "包含徽章/表情活动（无关联）",
        ["Badge_Sub"] = "订阅",
        ["Campaigns_BuyDrop"] = "购买掉宝",
        ["Settings_AutoClaimChannelPoints"] = "在所观看的频道自动领取频道积分",
        ["Settings_WhenOverridingHarvest"] = "覆盖时，收取",
        ["Settings_WhenOverridingHarvestDescription"] = "在某个活动上点击“收取”会执行的操作：整个活动、仅其下一个 Drop（然后回到自动），或每次询问。",
        ["Settings_PriorityGames"] = "优先游戏（置顶 = 最先）",
        ["Settings_StartTypingGameName"] = "开始输入游戏名称...",
        ["Settings_Add"] = "添加",
        ["Settings_DragToReorder"] = "拖动 ≡ 手柄以重新排序（或使用箭头）。置顶 = 最先收取。",
        ["Settings_ExcludedGames"] = "排除的游戏",
        ["Settings_ExcludedGamesDescription"] = "此列表中的游戏永不收取 - 其 Drop 活动会被完全跳过，即使游戏已关联且有直播。用它来忽略你不想要 Drops 的游戏。",
        ["Settings_DedupeGames"] = "去重游戏",
        ["Settings_DedupeGamesDescription"] = "对于添加到此处的游戏，跳过你已拥有奖励的 Drops（依据 Twitch 约 6 个月的领取历史）。",
        ["Settings_HarvestUnlinkedGames"] = "收取未关联的游戏",
        ["Settings_HarvestUnlinkedGamesDescription"] = "即使没有账户关联，也收取这些游戏的活动。总是最后收取（在所有已关联的活动之后），如果活动实际需要关联，可能不会记入。",
        ["Settings_PreferredChannels"] = "偏好频道（⭐）",
        ["Settings_PreferredChannelsDescription"] = "在下方添加一个频道，或在频道标签页中右键点击某个频道。当偏好频道正在直播所收取的游戏且不要求官方活动频道时，DropHarvester 会挂在它上面，而不是随机的高观众直播 - Drop 仍会记入，因此你可以在不影响收取的情况下支持该直播主。优先/最快结束仍决定收取哪个游戏；官方频道始终优先。",
        ["Settings_PreferredChannelPlaceholder"] = "频道登录名（例如 ninja）",
        ["Settings_NoChannelsYet"] = "暂无 - 在上方添加，或右键点击某个频道。",
        ["Settings_AvoidedChannels"] = "回避频道（🚫）",
        ["Settings_AvoidedChannelsDescription"] = "在下方添加一个频道，或在频道标签页中右键点击某个频道。回避的频道绝不会被挂载，除非它是当前该游戏唯一启用 Drops 的在线直播（最后手段）。",
        ["Settings_AvoidedChannelPlaceholder"] = "频道登录名（例如 somestreamer）",
        ["Settings_DropClaimedSound"] = "DROP 领取声音",
        ["Settings_PlaySoundOnDropClaimed"] = "领取 Drop 时播放声音",
        ["Settings_Choose"] = "选择...",
        ["Settings_Test"] = "测试",
        ["Settings_ClearSound"] = "清除声音",
        ["Settings_Volume"] = "音量",
        ["Settings_OutputDevice"] = "输出设备（Windows 可指向任意设备；macOS 使用系统默认）",
        ["Settings_DesktopNotifications"] = "桌面通知",
        ["Settings_DropClaimed"] = "Drop 已领取",
        ["Settings_CampaignComplete"] = "活动完成",
        ["Settings_AllDropsHarvested"] = "所有 Drops 已收取",
        ["Settings_LoginExpired"] = "登录已过期",
        ["Settings_RemoteWebhookAlerts"] = "远程 WEBHOOK 提醒",
        ["Settings_EnableWebhookAlerts"] = "启用 Webhook 提醒",
        ["Settings_WebhookType"] = "Webhook 类型",
        ["Settings_WebhookUrl"] = "Webhook URL",
        ["Settings_SendTestMessage"] = "发送测试消息",
        ["Settings_SendOn"] = "发送时机",
        ["Settings_NewDropAvailable"] = "游戏有新的 Drop 可领取",
        ["Settings_Log"] = "日志",
        ["Settings_TimestampOnEachLine"] = "在每行日志上显示时间戳",
        ["Settings_Application"] = "应用程序",
        ["Settings_MinimizeToTray"] = "关闭时最小化到托盘",
        ["Settings_StartWithSystem"] = "随系统启动",
        ["Settings_StartMinimizedToTray"] = "启动时最小化到托盘",
        ["Settings_StartMinimizedToTrayDescription"] = "每次启动都直接进入托盘而不显示在屏幕上 - 无论是你自己打开还是随系统启动。",
        ["Settings_ProxyOptional"] = "代理（可选）",
        ["Settings_ProxyPlaceholder"] = "http://host:port",
        ["Settings_DebugServer"] = "调试服务器",
        ["Settings_RunLocalDebugServer"] = "运行本地调试服务器",
        ["Settings_RunLocalDebugServerDescription"] = "在 localhost 上以 JSON 形式公开实时状态以及每个收取/跳过/领取决策 - 用于诊断应用在底层的行为。",
        ["Settings_Port"] = "端口",

        // ----- engine status + common log lines -----
        ["Status_Starting"] = "启动中...",
        ["Status_Stopped"] = "已停止",
        ["Status_NoDropsToHarvest"] = "没有可收取的 Drops",
        ["Status_WaitingForStream"] = "有可用的 Drops - 正在等待直播上线",
        ["Status_WatchingChannelGame"] = "正在观看 {0} - {1}",
        ["Status_ChannelWentOffline"] = "{0} 已离线",
        ["Log_HarvestingStarted"] = "收取已开始。",
        ["Log_HarvestingStopped"] = "收取已停止。",
        ["Log_ConnectionReestablished"] = "连接已重新建立 - 恢复收取。",
        ["Log_ConnectionLost"] = "Twitch Drops 似乎已宕机或连接已丢失 - 收取已暂停；恢复后将自动继续。",

        // ----- Status/login view-model strings -----
        ["Status_Idle"] = "空闲",
        ["Status_NotLoggedIn"] = "未登录",
        ["Status_LoggedInAs"] = "已登录为 {0}（id {1}）",
        ["Status_ConnectionIssue"] = "Twitch Drops 出现问题或你已失去连接。连接重新建立后我们将自动恢复收取。",
        ["Status_DropsOutage"] = "Twitch 目前接受观看，但不再累计掉宝进度（Twitch 服务端故障）。收取会持续运行，恢复后将自动继续。",
        ["Login_Requesting"] = "正在向 Twitch 请求登录代码...",
        ["Login_GoToAndEnter"] = "前往 {0} 并输入代码 {1}",
        ["Login_NotCompleted"] = "登录未完成。请重试。",
        ["Login_Cancelled"] = "登录已取消。",
        ["Login_Failed"] = "登录失败：{0}",
        ["Login_Expired"] = "你的 Twitch 会话已过期 - 请重新登录。",
        ["Override_HarvestPrompt"] = "覆盖 - 收取：",
        ["Override_JustNextDrop"] = "仅下一个 Drop",
        ["Override_EntireCampaign"] = "整个活动",
        ["Override_AskEachTime"] = "每次询问我",

        // ----- Inventory load status -----
        ["Inventory_LoadingDrops"] = "正在加载 Drops... {0}/{1}",
        ["Inventory_Loaded"] = "{0} 个活动。",
        ["Inventory_None"] = "未找到活动。",
        ["Inventory_LoadFailed"] = "加载失败：{0}",

        // ----- Channels view-model -----
        ["Channels_CountText"] = "{1} 个游戏中共有 {0} 个在线频道",
        ["Channels_UnknownGame"] = "未知",
        ["Channels_OneLive"] = "1 个在线",
        ["Channels_NLive"] = "{0} 个在线",

        // ----- Campaigns view-model -----
        ["Campaigns_ListView"] = "列表视图",
        ["Campaigns_GridView"] = "网格视图",
        ["Inventory_LogInFirst"] = "请先登录以查看你的库存。",
        ["Inventory_LoadingCampaigns"] = "正在加载活动...",

        // ----- Stats view-model -----
        ["Stats_ExportedJson"] = "已导出 JSON 至 {0}",
        ["Stats_ExportedCsv"] = "已导出 CSV 至 {0}",
        ["Stats_Since"] = "自 {0} 起",

        // ----- Log view-model -----
        ["Log_Copy"] = "复制",
        ["Log_Copied"] = "已复制！",
        ["Log_CopyFailed"] = "复制失败",

        // ----- Settings view-model -----
        ["Settings_NoSoundChosen"] = "未选择声音",
        ["Settings_ChooseSoundTitle"] = "选择领取 Drop 时播放的声音",
        ["Settings_SoundPickFailed"] = "无法选取文件：{0}",
        ["Settings_AudioNotAvailable"] = "此平台不支持音频播放。",
        ["Settings_ChooseSoundFirst"] = "请先选择一个声音文件。",
        ["Settings_SystemDefault"] = "系统默认",
        ["Settings_PlayingOn"] = "正在 {0} 上以 {1} 播放...",
        ["Settings_InvalidGameHint"] = "不是有效的 Twitch 游戏 - 请选择一个建议项。",
        ["Settings_TimestampDate"] = "日期",
        ["Settings_TimestampTime"] = "时间",
        ["Settings_TimestampDateAndTime"] = "日期和时间",
        ["Settings_TimestampTimeAndDate"] = "时间和日期",
        ["Settings_Clock12Hour"] = "12 小时制",
        ["Settings_Clock24Hour"] = "24 小时制",
        ["Settings_CurrentVersion"] = "你当前使用 v{0}。",
        ["Settings_UpdateReadyStatus"] = "更新 v{0} 已就绪 - 点击“立即更新”以安装。",
        ["Settings_CheckingForUpdates"] = "正在检查更新...",
        ["Settings_UpdateServerUnreachable"] = "无法连接到更新服务器。",
        ["Settings_OnLatestVersion"] = "你已是最新版本（v{0}）。",
        ["Settings_DownloadingUpdate"] = "正在下载更新 v{0}...",
        ["Settings_UpdateReadyAutoInstall"] = "更新 v{0} 已就绪 - 点击“立即更新”以安装，或在下次重启时自动安装。",
        ["Settings_UpdateDownloadFailed"] = "更新下载失败 - 请重试。",
        ["Settings_UpdateCheckFailed"] = "更新检查失败。",
        ["Settings_InstallingUpdate"] = "正在安装更新 - 应用将重启...",
        ["Settings_InstallerStartFailed"] = "无法启动安装程序 - 将在下次重启时自动安装。",
        ["Settings_DebugServerRunning"] = "运行中 - 打开 {0}（仅限 localhost）",
        ["Settings_DebugServerOff"] = "关闭",
        ["Settings_Hide"] = "隐藏",
        ["Settings_Show"] = "显示",
        ["Settings_WebhookGeneric"] = "通用",
        ["Settings_Sending"] = "发送中...",
        ["Settings_WebhookEnterUrlFirst"] = "请先输入 Webhook URL。",
        ["Settings_WebhookTestSent"] = "测试消息已发送。",
        ["Settings_WebhookReturnedError"] = "Webhook 返回了一个错误。",
        ["Settings_WebhookFailed"] = "失败：{0}",

        // ----- Twitch model display -----
        ["Model_RemovePreferred"] = "⭐ 移除偏好",
        ["Model_PreferChannel"] = "⭐ 偏好此频道",
        ["Model_RemoveAvoided"] = "\U0001F6AB 移除回避",
        ["Model_AvoidChannel"] = "\U0001F6AB 回避此频道",
        ["Model_ChannelLive"] = "直播中 - {0}",
        ["Model_ChannelOffline"] = "离线",
        ["Model_DropProgress"] = "{0}/{1} 分钟",
        ["Model_DropProgressSummary"] = "{0}  （{1}/{2} 分钟）",
        ["Model_Remaining"] = "剩余 {0}",
        ["Model_Linked"] = "已关联",
        ["Model_LinkNeeded"] = "需要关联",
        ["Model_Ends"] = "结束于 {0}",
    };
}
