namespace DropHarvester.Localization;

/// <summary>The English base string table (key -> text). Every other language falls back to these for any
/// key it hasn't translated, so English is always complete.</summary>
public static partial class LocStrings
{
    public static readonly Dictionary<string, string> En = new(StringComparer.Ordinal)
    {
        // ----- common -----
        ["Common_Cancel"] = "Cancel",
        ["Common_Harvest"] = "Harvest",
        ["Common_Harvesting"] = "Harvesting",

        // ----- tab titles -----
        ["Tab_Status"] = "Status",
        ["Tab_Inventory"] = "Inventory",
        ["Tab_Channels"] = "Channels",
        ["Tab_Settings"] = "Settings",
        ["Tab_Log"] = "Log",
        ["Tab_Stats"] = "Stats",

        // ----- Status page -----
        ["Status_UpdateReady"] = "Update ready",
        ["Status_UpdateNow"] = "Update now",
        ["Status_UpdateAvailableTitle"] = "Update available",
        ["Status_UpdateAvailableDetail"] = "Version v{0} is available - it's highly recommended to update.",
        ["Status_UpdateDownloading"] = "Downloading v{0}...",
        ["Status_Download"] = "Download",
        ["Status_Account"] = "ACCOUNT",
        ["Status_LogIn"] = "Log in with Twitch",
        ["Status_LogOut"] = "Log out",
        ["Status_AuthorizeHeader"] = "AUTHORIZE THIS APP",
        ["Status_AuthorizeBody"] = "A browser window was opened. Enter this code to link your Twitch account:",
        ["Status_Harvesting"] = "HARVESTING",
        ["Status_StartHarvesting"] = "Start harvesting",
        ["Status_PauseHarvesting"] = "Pause harvesting",
        ["Status_Channel"] = "Channel",
        ["Status_Game"] = "Game",
        ["Status_Campaign"] = "Campaign",
        ["Status_WatchLive"] = "Watch Live",
        ["Status_CampaignProgress"] = "Campaign progress",
        ["Status_UpNext"] = "UP NEXT",
        ["Status_Queue"] = "QUEUE",
        ["Status_RemoveOverride"] = "Remove override",
        ["Status_AllowNewHigherPriority"] = "Allow new higher priority campaigns to end this override",

        // ----- Settings: language -----
        ["Settings_Language"] = "Language",
        ["Settings_LanguageNav"] = "Language",

        // ----- notifications -----
        ["Notif_NameDashGame"] = "{0} - {1}",
        ["Notif_DropClaimed"] = "Drop claimed",
        ["Notif_CampaignComplete"] = "Campaign complete",
        ["Notif_AllHarvested"] = "All drops harvested",
        ["Notif_AllHarvestedBody"] = "No more drops available to harvest right now.",
        ["Notif_NewDrop"] = "New drop available",
        ["Notif_LoginExpired"] = "Login expired",
        ["Notif_LoginExpiredBody"] = "Your Twitch session expired - please log in again.",

        // ----- Campaigns / Inventory page -----
        ["Campaigns_Refresh"] = "Refresh",
        ["Campaigns_Upcoming"] = "Upcoming",
        ["Campaigns_Expired"] = "Expired",
        ["Campaigns_NotLinked"] = "Not linked",
        ["Campaigns_Finished"] = "Finished",
        ["Campaigns_Excluded"] = "Excluded",
        ["Campaigns_Deduped"] = "De-duped",
        ["Campaigns_NoMatch"] = "No campaigns match the current filters.",
        ["Campaigns_Harvesting"] = "Harvesting",
        ["Campaigns_Claimed"] = "Claimed",
        ["Campaigns_ClaimedBadge"] = "Claimed",

        // ----- Channels page -----
        ["Channels_Updating"] = "Updating...",
        ["Channels_EmptyView"] = "No channels tracked yet. Harvesting populates this once a campaign is active.",
        ["Channels_Channel"] = "CHANNEL",
        ["Channels_Official"] = "OFFICIAL",
        ["Channels_Viewers"] = "VIEWERS",
        ["Channels_Status"] = "STATUS",
        ["Channels_Watch"] = "Watch",
        ["Channels_Switching"] = "Switching...",
        ["Channels_Harvesting"] = "Harvesting",

        // ----- Stats page -----
        ["Stats_DropsClaimed"] = "Drops claimed",
        ["Stats_CampaignsDone"] = "Campaigns done",
        ["Stats_WatchTimeSaved"] = "Time spent harvesting",
        ["Stats_DropsClaimedLast7Days"] = "DROPS CLAIMED (LAST 7 DAYS)",
        ["Stats_ExportCsv"] = "Export CSV",
        ["Stats_ExportJson"] = "Export JSON",
        ["Stats_RecentHistory"] = "RECENT HISTORY",
        ["Stats_NoHistoryYet"] = "No history yet.",

        // ----- Log page -----
        ["Log_Clear"] = "Clear",
        ["Log_NoLogOutputYet"] = "No log output yet.",

        // ----- Settings page -----
        ["Settings_Settings"] = "SETTINGS",
        ["Settings_NavUpdates"] = "Updates",
        ["Settings_NavHarvesting"] = "Harvesting",
        ["Settings_NavPriorityGames"] = "Priority games",
        ["Settings_NavExcludedGames"] = "Excluded games",
        ["Settings_NavDedupeGames"] = "De-dupe games",
        ["Settings_NavUnlinkedGames"] = "Unlinked games",
        ["Settings_NavPreferredChannels"] = "Preferred channels",
        ["Settings_NavAvoidedChannels"] = "Avoided channels",
        ["Settings_NavDropSound"] = "Drop sound",
        ["Settings_NavNotifications"] = "Notifications",
        ["Settings_NavWebhookAlerts"] = "Webhook alerts",
        ["Settings_NavLog"] = "Log",
        ["Settings_NavApplication"] = "Application",
        ["Settings_NavDebugServer"] = "Debug server",
        ["Settings_Updates"] = "UPDATES",
        ["Settings_AutoCheckUpdates"] = "Check for updates automatically on startup",
        ["Settings_UpdatesDescription"] = "Checks GitHub for a new version on startup and once a day. When one's available, a banner on the Status tab lets you download it, then install it here or there - or it auto-installs on the next restart.",
        ["Settings_CheckNow"] = "Check now",
        ["Settings_UpdateNow"] = "Update now",
        ["Settings_Harvesting"] = "HARVESTING",
        ["Settings_HarvestOnlyPriority"] = "Harvest only priority games",
        ["Settings_PrioritizeEndingSoonest"] = "Prioritize ending soonest",
        ["Settings_PrioritizeEndingSoonestDescription"] = "Harvest whichever eligible campaign expires first - but still honor the priority list when there's time: a priority drop is harvested ahead of a sooner one whenever deferring it wouldn't lose it, and a sooner non-priority drop is only chosen if it won't cost you a priority drop.",
        ["Settings_PrioritizeByAvailability"] = "Prioritize by availability",
        ["Settings_PrioritizeByAvailabilityDescription"] = "Tiebreaker only: when campaigns are otherwise tied in the order above, harvest the one whose game has fewer live drops-enabled streamers first - grabbing scarce-stream drops while a channel is live and letting plentiful games wait. Never overrides your priority list.",
        ["Settings_HarvestImpossibleDrops"] = "Harvest impossible drops",
        ["Settings_HarvestImpossibleDropsDescription"] = "Watch drops that can't finish before the campaign ends (in case it gets extended).",
        ["Settings_ShowUnlinkedInChannels"] = "Show unlinked games in Channels",
        ["Settings_ShowUnlinkedInChannelsDescription"] = "Off by default. Skipping unlinked games' channels saves directory lookups (API calls).",
        ["Settings_IncludeBadgeEmote"] = "Include badge/emote campaigns (no link)",
        ["Settings_AutoClaimChannelPoints"] = "Auto-claim channel points on watched channel",
        ["Settings_WhenOverridingHarvest"] = "When overriding, harvest",
        ["Settings_WhenOverridingHarvestDescription"] = "What clicking \"Harvest\" on a campaign does: the whole campaign, just its next drop (then back to auto), or ask each time.",
        ["Settings_PriorityGames"] = "PRIORITY GAMES (TOP = FIRST)",
        ["Settings_StartTypingGameName"] = "Start typing a game name...",
        ["Settings_Add"] = "Add",
        ["Settings_DragToReorder"] = "Drag by the ≡ handle to reorder (or use the arrows). Top = harvested first.",
        ["Settings_ExcludedGames"] = "EXCLUDED GAMES",
        ["Settings_ExcludedGamesDescription"] = "Games on this list are never harvested - their drop campaigns are skipped entirely, even when the game is linked and has live streams. Use it to ignore games you don't want drops for.",
        ["Settings_DedupeGames"] = "DE-DUPE GAMES",
        ["Settings_DedupeGamesDescription"] = "For games added here, skip drops whose reward you already own (from Twitch's ~6-month claim history).",
        ["Settings_HarvestUnlinkedGames"] = "HARVEST UNLINKED GAMES",
        ["Settings_HarvestUnlinkedGamesDescription"] = "Harvest these games' campaigns even without an account link. Always harvested LAST (below every linked campaign), and may not credit if the campaign actually requires a link.",
        ["Settings_PreferredChannels"] = "PREFERRED CHANNELS (⭐)",
        ["Settings_PreferredChannelsDescription"] = "Add a channel below, or right-click one in the Channels tab. When a preferred channel is live for the game being harvested and no official campaign channel is required, DropHarvester idles on it instead of a random top-viewer stream - the drop still credits, so you support the streamer at no cost to harvesting. Priority/ending-soonest still decides which game is harvested; an official channel always wins.",
        ["Settings_PreferredChannelPlaceholder"] = "Channel login (e.g. ninja)",
        ["Settings_NoChannelsYet"] = "None yet - add one above or by right-clicking a channel.",
        ["Settings_AvoidedChannels"] = "AVOIDED CHANNELS (🚫)",
        ["Settings_AvoidedChannelsDescription"] = "Add a channel below, or right-click one in the Channels tab. An avoided channel is never idled on unless it's the only drops-enabled stream live for the game right now (last resort).",
        ["Settings_AvoidedChannelPlaceholder"] = "Channel login (e.g. somestreamer)",
        ["Settings_DropClaimedSound"] = "DROP-CLAIMED SOUND",
        ["Settings_PlaySoundOnDropClaimed"] = "Play a sound when a drop is claimed",
        ["Settings_Choose"] = "Choose...",
        ["Settings_Test"] = "Test",
        ["Settings_ClearSound"] = "Clear sound",
        ["Settings_Volume"] = "Volume",
        ["Settings_OutputDevice"] = "Output device (Windows can target any device; macOS uses the system default)",
        ["Settings_DesktopNotifications"] = "DESKTOP NOTIFICATIONS",
        ["Settings_DropClaimed"] = "Drop claimed",
        ["Settings_CampaignComplete"] = "Campaign complete",
        ["Settings_AllDropsHarvested"] = "All drops harvested",
        ["Settings_LoginExpired"] = "Login expired",
        ["Settings_RemoteWebhookAlerts"] = "REMOTE WEBHOOK ALERTS",
        ["Settings_EnableWebhookAlerts"] = "Enable webhook alerts",
        ["Settings_WebhookType"] = "Webhook type",
        ["Settings_WebhookUrl"] = "Webhook URL",
        ["Settings_SendTestMessage"] = "Send test message",
        ["Settings_SendOn"] = "SEND ON",
        ["Settings_NewDropAvailable"] = "New drop available for game",
        ["Settings_Log"] = "LOG",
        ["Settings_TimestampOnEachLine"] = "Timestamp shown on each log line",
        ["Settings_Application"] = "APPLICATION",
        ["Settings_MinimizeToTray"] = "Minimize to tray on close",
        ["Settings_StartWithSystem"] = "Start with the system",
        ["Settings_StartMinimizedToTray"] = "Start minimized to the tray",
        ["Settings_StartMinimizedToTrayDescription"] = "Launch straight to the tray instead of on screen - every launch, whether you open it yourself or it starts with the system.",
        ["Settings_ProxyOptional"] = "Proxy (optional)",
        ["Settings_ProxyPlaceholder"] = "http://host:port",
        ["Settings_DebugServer"] = "DEBUG SERVER",
        ["Settings_RunLocalDebugServer"] = "Run local debug server",
        ["Settings_RunLocalDebugServerDescription"] = "Exposes live state and every harvest/skip/claim decision as JSON on localhost - for diagnosing what the app is doing under the hood.",
        ["Settings_Port"] = "Port",

        // ----- engine status + common log lines -----
        ["Status_Starting"] = "Starting...",
        ["Status_Stopped"] = "Stopped",
        ["Status_NoDropsToHarvest"] = "No drops to harvest",
        ["Status_WaitingForStream"] = "Drops available - waiting for a stream to come online",
        ["Status_WatchingChannelGame"] = "Watching {0} - {1}",
        ["Status_ChannelWentOffline"] = "{0} went offline",
        ["Log_HarvestingStarted"] = "Harvesting started.",
        ["Log_HarvestingStopped"] = "Harvesting stopped.",
        ["Log_ConnectionReestablished"] = "Connection re-established - resuming harvesting.",
        ["Log_ConnectionLost"] = "Twitch Drops appear to be down or the connection was lost - harvesting paused; will resume automatically once it's back.",

        // ----- Status/login view-model strings -----
        ["Status_Idle"] = "Idle",
        ["Status_NotLoggedIn"] = "Not logged in",
        ["Status_LoggedInAs"] = "Logged in as {0} (id {1})",
        ["Status_ConnectionIssue"] = "Twitch Drops are experiencing issues or you've lost connection. We'll automatically resume harvesting once connection has been re-established.",
        ["Login_Requesting"] = "Requesting a login code from Twitch...",
        ["Login_GoToAndEnter"] = "Go to {0} and enter code {1}",
        ["Login_NotCompleted"] = "Login was not completed. Please try again.",
        ["Login_Cancelled"] = "Login cancelled.",
        ["Login_Failed"] = "Login failed: {0}",
        ["Login_Expired"] = "Your Twitch session expired - please log in again.",
        ["Override_HarvestPrompt"] = "Override - harvest:",
        ["Override_JustNextDrop"] = "Just the next drop",
        ["Override_EntireCampaign"] = "Entire campaign",
        ["Override_AskEachTime"] = "Ask me each time",

        // ----- Inventory load status -----
        ["Inventory_LoadingDrops"] = "Loading drops... {0}/{1}",
        ["Inventory_Loaded"] = "{0} campaigns.",
        ["Inventory_None"] = "No campaigns found.",
        ["Inventory_LoadFailed"] = "Failed to load: {0}",

        // ----- Channels view-model -----
        ["Channels_CountText"] = "{0} live channels across {1} games",
        ["Channels_UnknownGame"] = "Unknown",
        ["Channels_OneLive"] = "1 live",
        ["Channels_NLive"] = "{0} live",

        // ----- Campaigns view-model -----
        ["Campaigns_ListView"] = "List view",
        ["Campaigns_GridView"] = "Grid view",
        ["Inventory_LogInFirst"] = "Log in first to see your inventory.",
        ["Inventory_LoadingCampaigns"] = "Loading campaigns...",

        // ----- Stats view-model -----
        ["Stats_ExportedJson"] = "Exported JSON to {0}",
        ["Stats_ExportedCsv"] = "Exported CSV to {0}",
        ["Stats_Since"] = "Since {0}",

        // ----- Log view-model -----
        ["Log_Copy"] = "Copy",
        ["Log_Copied"] = "Copied!",
        ["Log_CopyFailed"] = "Copy failed",

        // ----- Settings view-model -----
        ["Settings_NoSoundChosen"] = "No sound chosen",
        ["Settings_ChooseSoundTitle"] = "Choose a sound to play when a drop is claimed",
        ["Settings_SoundPickFailed"] = "Couldn't pick a file: {0}",
        ["Settings_AudioNotAvailable"] = "Audio playback isn't available on this platform.",
        ["Settings_ChooseSoundFirst"] = "Choose a sound file first.",
        ["Settings_SystemDefault"] = "System default",
        ["Settings_PlayingOn"] = "Playing on {0} at {1}...",
        ["Settings_InvalidGameHint"] = "Not a valid Twitch game - pick a suggestion.",
        ["Settings_TimestampDate"] = "Date",
        ["Settings_TimestampTime"] = "Time",
        ["Settings_TimestampDateAndTime"] = "Date and time",
        ["Settings_TimestampTimeAndDate"] = "Time and date",
        ["Settings_Clock12Hour"] = "12-hour clock",
        ["Settings_Clock24Hour"] = "24-hour clock",
        ["Settings_CurrentVersion"] = "You're on v{0}.",
        ["Settings_UpdateReadyStatus"] = "Update v{0} is ready - click Update now to install.",
        ["Settings_CheckingForUpdates"] = "Checking for updates...",
        ["Settings_UpdateServerUnreachable"] = "Couldn't reach the update server.",
        ["Settings_OnLatestVersion"] = "You're on the latest version (v{0}).",
        ["Settings_DownloadingUpdate"] = "Downloading update v{0}...",
        ["Settings_UpdateReadyAutoInstall"] = "Update v{0} is ready - click Update now to install, or it auto-installs on next restart.",
        ["Settings_UpdateDownloadFailed"] = "Update download failed - try again.",
        ["Settings_UpdateCheckFailed"] = "Update check failed.",
        ["Settings_InstallingUpdate"] = "Installing update - the app will restart...",
        ["Settings_InstallerStartFailed"] = "Couldn't start the installer - it'll auto-install on next restart.",
        ["Settings_DebugServerRunning"] = "Running - open {0} (localhost only)",
        ["Settings_DebugServerOff"] = "Off",
        ["Settings_Hide"] = "Hide",
        ["Settings_Show"] = "Show",
        ["Settings_WebhookGeneric"] = "Generic",
        ["Settings_Sending"] = "Sending...",
        ["Settings_WebhookEnterUrlFirst"] = "Enter a webhook URL first.",
        ["Settings_WebhookTestSent"] = "Test message sent.",
        ["Settings_WebhookReturnedError"] = "Webhook returned an error.",
        ["Settings_WebhookFailed"] = "Failed: {0}",

        // ----- Twitch model display -----
        ["Model_RemovePreferred"] = "⭐ Remove preferred",
        ["Model_PreferChannel"] = "⭐ Prefer this channel",
        ["Model_RemoveAvoided"] = "\U0001F6AB Remove avoided",
        ["Model_AvoidChannel"] = "\U0001F6AB Avoid this channel",
        ["Model_ChannelLive"] = "LIVE - {0}",
        ["Model_ChannelOffline"] = "offline",
        ["Model_DropProgress"] = "{0}/{1} min",
        ["Model_DropProgressSummary"] = "{0}  ({1}/{2} min)",
        ["Model_Remaining"] = "{0} remaining",
        ["Model_Linked"] = "Linked",
        ["Model_LinkNeeded"] = "Link needed",
        ["Model_Ends"] = "Ends {0}",
    };
}
